export { aiRouter } from "./ai";
export { communicationRouter, complianceRouter, crisisRouter, fieldRouter, followupsRouter, insightsRouter, monitoringRouter, operationsRouter, planningRouter, publicEventsRouter, reportsRouter, territoryRouter } from "./campaign";
export { campaignRouter } from "./campaignBasics";
export { dashboardRouter } from "./dashboard";
export { goalsRouter } from "./goals";
export { tasksRouter } from "./tasks";
export { teamRouter } from "./team";
export { consentRouter, contentsRouter, financeLegalRouter, votersRouter } from "./criticalWrites";
export { publicIntakeRouter, volunteersRouter } from "./publicProtection";
export { organizationRouter } from "./organization";
export { platformAdminRouter } from "./platformAdmin";
