import { PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { startRegistration } from "@simplewebauthn/browser";
import QRCode from "qrcode";
import { Fingerprint, KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AccountSecurity() {
  const utils = trpc.useUtils(); const status = trpc.auth.securityStatus.useQuery(); const beginPasskey = trpc.auth.beginPasskeyEnrollment.useMutation(); const finishPasskey = trpc.auth.finishPasskeyEnrollment.useMutation({ onSuccess: () => { toast.success("Passkey cadastrada com segurança."); void utils.auth.securityStatus.invalidate(); } }); const beginMfa = trpc.auth.beginMfaEnrollment.useMutation(); const confirmMfa = trpc.auth.confirmMfaEnrollment.useMutation({ onSuccess: () => { toast.success("MFA ativado."); setMfaSecret(""); setQrCode(""); void utils.auth.securityStatus.invalidate(); } }); const setLocalPassword = trpc.auth.setLocalPassword.useMutation({ onSuccess: () => { toast.success("Senha local configurada com segurança."); setPassword(""); setPasswordConfirmation(""); setCurrentPassword(""); void utils.auth.securityStatus.invalidate(); }, onError: error => toast.error(error.message === "CURRENT_PASSWORD_REQUIRED" ? "Informe a senha atual para alterá-la." : "Não foi possível configurar a senha local.") });
  const [mfaSecret, setMfaSecret] = useState(""); const [qrCode, setQrCode] = useState(""); const [mfaCode, setMfaCode] = useState(""); const [password, setPassword] = useState(""); const [passwordConfirmation, setPasswordConfirmation] = useState(""); const [currentPassword, setCurrentPassword] = useState("");
  const registerPasskey = async () => { try { const { options, label } = await beginPasskey.mutateAsync({ origin: window.location.origin, label: "Passkey deste dispositivo" }); const response = await startRegistration({ optionsJSON: options }); await finishPasskey.mutateAsync({ origin: window.location.origin, label, response }); } catch { toast.error("Não foi possível cadastrar a passkey neste dispositivo."); } };
  const setupMfa = async () => { try { const result = await beginMfa.mutateAsync(); setMfaSecret(result.enrollmentSecret); setQrCode(await QRCode.toDataURL(result.otpauthUrl, { width: 220, margin: 1 })); } catch { toast.error("Não foi possível iniciar a configuração MFA."); } };
  return <section><PageHeader eyebrow="Proteção da conta" title="Segurança de acesso" description="Fortaleça a conta com passkey e autenticação em dois fatores. O login por senha continua disponível como alternativa." action={<Badge variant="outline" className="gap-1.5"><ShieldCheck className="size-3.5" />Proteção ativa</Badge>} />
    <div className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border bg-card p-6 shadow-sm"><LockKeyhole className="size-6 text-primary" /><h2 className="mt-4 font-serif text-2xl">Senha local</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Defina uma senha para acessar a mesma conta também por e-mail. Ela não cria uma segunda conta nem altera sua identidade Google.</p><div className="mt-4"><Badge variant={status.data?.localPasswordEnabled ? "default" : "outline"}>{status.data?.localPasswordEnabled ? "Configurada" : "Ainda não configurada"}</Badge></div><div className="mt-5 grid gap-3">{status.data?.localPasswordEnabled && <div><Label htmlFor="current-password">Senha atual</Label><Input id="current-password" type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} autoComplete="current-password" /></div>}<div><Label htmlFor="new-password">Nova senha</Label><Input id="new-password" type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="new-password" minLength={10} /></div><div><Label htmlFor="confirm-password">Confirmar nova senha</Label><Input id="confirm-password" type="password" value={passwordConfirmation} onChange={event => setPasswordConfirmation(event.target.value)} autoComplete="new-password" minLength={10} /></div><Button onClick={() => setLocalPassword.mutate({ password, currentPassword: status.data?.localPasswordEnabled ? currentPassword : undefined })} disabled={password.length < 10 || password !== passwordConfirmation || (status.data?.localPasswordEnabled && !currentPassword) || setLocalPassword.isPending}>Salvar senha local</Button></div></article><article className="rounded-2xl border bg-card p-6 shadow-sm"><Fingerprint className="size-6 text-primary" /><h2 className="mt-4 font-serif text-2xl">Passkey</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Use biometria, PIN ou bloqueio do aparelho para entrar sem digitar senha e com proteção contra páginas falsas.</p><div className="mt-4"><Badge variant={status.data?.passkeysEnabled ? "default" : "outline"}>{status.data?.passkeysEnabled ? "Configurada" : "Ainda não configurada"}</Badge></div><Button className="mt-5" onClick={() => void registerPasskey()} disabled={beginPasskey.isPending || finishPasskey.isPending}><KeyRound className="mr-2 size-4" />Cadastrar passkey neste dispositivo</Button></article>
      <article className="rounded-2xl border bg-card p-6 shadow-sm"><ShieldCheck className="size-6 text-primary" /><h2 className="mt-4 font-serif text-2xl">Autenticação em dois fatores</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Confirme o acesso com um código de seis dígitos do seu aplicativo autenticador.</p><div className="mt-4"><Badge variant={status.data?.mfaEnabled ? "default" : "outline"}>{status.data?.mfaEnabled ? "Ativada" : "Ainda não ativada"}</Badge></div>{!mfaSecret ? <Button className="mt-5" onClick={() => void setupMfa()} disabled={beginMfa.isPending}>Configurar MFA</Button> : <div className="mt-5 rounded-xl border border-primary/20 bg-primary/[.035] p-4"><p className="text-sm font-semibold">1. Leia o QR Code no autenticador</p>{qrCode && <img src={qrCode} alt="QR Code para configurar MFA" className="mt-3 size-44 rounded-lg bg-white p-2" />}<p className="mt-4 text-sm font-semibold">2. Informe o código gerado</p><Label htmlFor="mfa-confirm" className="sr-only">Código MFA</Label><Input id="mfa-confirm" value={mfaCode} onChange={event => setMfaCode(event.target.value.replace(/\D/g, ""))} maxLength={6} inputMode="numeric" placeholder="000000" className="mt-2 max-w-48 tracking-[.35em]" /><Button className="mt-3" disabled={mfaCode.length !== 6 || confirmMfa.isPending} onClick={() => confirmMfa.mutate({ enrollmentSecret: mfaSecret, code: mfaCode })}>Ativar MFA</Button></div>}</article></div></section>;
}
