import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { ChevronLeft, ChevronRight, CalendarPlus, MapPin, Plus } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const types = { meeting: "Reunião", rally: "Comício", visit: "Visita", debate: "Debate", internal: "Interno", other: "Outro" };
function monthBounds(cursor: Date) { return { start: new Date(cursor.getFullYear(), cursor.getMonth(), 1), end: new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0, 23, 59, 59) }; }

function AgendaContent() {
  const { activeCampaign } = useCampaign();
  const [cursor, setCursor] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [openForm, setOpenForm] = useState(false);
  const [editingEventId, setEditingEventId] = useState<number | null>(null);
  const [form, setForm] = useState({ title: "", type: "meeting" as keyof typeof types, startsAt: "", location: "", neighborhood: "", region: "", notes: "" });
  const bounds = useMemo(() => monthBounds(cursor), [cursor]);
  const { data: eventList, refetch } = trpc.planning.list.useQuery({ campaignId: activeCampaign!.id, startsAt: bounds.start, endsAt: bounds.end });
  const createEvent = trpc.planning.create.useMutation({ onSuccess: () => { toast.success("Compromisso agendado."); setOpenForm(false); setForm({ title: "", type: "meeting", startsAt: "", location: "", neighborhood: "", region: "", notes: "" }); void refetch(); }, onError: error => toast.error(error.message) });
  const updateEvent = trpc.planning.update.useMutation({ onSuccess: () => { toast.success("Compromisso atualizado."); setOpenForm(false); setEditingEventId(null); setForm({ title: "", type: "meeting", startsAt: "", location: "", neighborhood: "", region: "", notes: "" }); void refetch(); }, onError: error => toast.error(error.message) });
  const canManage = activeCampaign?.memberRole !== "partner";
  const days = useMemo(() => { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const total = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate(); return Array.from({ length: 42 }, (_, index) => index - offset + 1).map(day => day > 0 && day <= total ? new Date(cursor.getFullYear(), cursor.getMonth(), day) : null); }, [cursor]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (editingEventId) { updateEvent.mutate({ eventId: editingEventId, title: form.title, type: form.type, startsAt: new Date(form.startsAt), location: form.location || undefined, neighborhood: form.neighborhood || undefined, region: form.region || undefined, notes: form.notes || undefined, status: "scheduled" }); } else { createEvent.mutate({ campaignId: activeCampaign!.id, title: form.title, type: form.type, startsAt: new Date(form.startsAt), location: form.location || undefined, neighborhood: form.neighborhood || undefined, region: form.region || undefined, notes: form.notes || undefined }); } };
  return <>
    <PageHeader eyebrow="Planejamento eleitoral" title="Agenda da campanha" description="Organize compromissos, mobilizações, visitas e reuniões em uma visão mensal compartilhada." action={canManage ? <Button onClick={() => setOpenForm(value => !value)} className="bg-[#103527] text-white hover:bg-[#174a35]"><CalendarPlus className="mr-2 size-4" />Novo compromisso</Button> : undefined} />
    {openForm && <form onSubmit={submit} className="mb-6 grid gap-4 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 md:grid-cols-2 xl:grid-cols-4"><div className="space-y-2"><Label>Título</Label><Input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Ex.: Reunião de coordenação" /></div><div className="space-y-2"><Label>Tipo</Label><select value={form.type} onChange={event => setForm({ ...form, type: event.target.value as keyof typeof types })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{Object.entries(types).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="space-y-2"><Label>Data e hora</Label><Input required type="datetime-local" value={form.startsAt} onChange={event => setForm({ ...form, startsAt: event.target.value })} /></div><div className="space-y-2"><Label>Local</Label><Input value={form.location} onChange={event => setForm({ ...form, location: event.target.value })} placeholder="Endereço ou referência" /></div><div className="space-y-2"><Label>Bairro</Label><Input value={form.neighborhood} onChange={event => setForm({ ...form, neighborhood: event.target.value })} placeholder="Ex.: Centro" /></div><div className="space-y-2"><Label>Região</Label><Input value={form.region} onChange={event => setForm({ ...form, region: event.target.value })} placeholder="Ex.: Norte" /></div><div className="space-y-2 md:col-span-2"><Label>Observações</Label><Textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} placeholder="Informações de apoio para a equipe" /></div><div className="flex items-end gap-2"><Button type="submit" className="flex-1" disabled={createEvent.isPending || updateEvent.isPending}>{createEvent.isPending || updateEvent.isPending ? "Salvando..." : editingEventId ? "Atualizar" : "Agendar"}</Button><Button type="button" variant="outline" onClick={() => { setOpenForm(false); setEditingEventId(null); }}>Cancelar</Button></div></form>}
    <section className="rounded-2xl border border-border/75 bg-card p-4 shadow-[0_12px_28px_-24px_rgba(0,0,0,.6)] sm:p-5"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="icon" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))}><ChevronLeft className="size-4" /></Button><h2 className="min-w-44 text-center font-serif text-xl capitalize">{new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(cursor)}</h2><Button variant="outline" size="icon" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))}><ChevronRight className="size-4" /></Button></div><Button variant="ghost" size="sm" onClick={() => setCursor(new Date(new Date().getFullYear(), new Date().getMonth(), 1))}>Hoje</Button></div><div className="grid grid-cols-7 border-l border-t border-border/60">{["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"].map(day => <div key={day} className="border-b border-r border-border/60 bg-muted/40 py-2 text-center text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{day}</div>)}{days.map((day, index) => { const dayEvents = day ? eventList?.filter(item => item.startsAt.toDateString() === day.toDateString()) ?? [] : []; const today = day?.toDateString() === new Date().toDateString(); return <div key={index} className="min-h-24 border-b border-r border-border/60 p-1.5 sm:min-h-28"><span className={`flex size-6 items-center justify-center rounded-full text-xs ${today ? "bg-primary font-bold text-primary-foreground" : "text-muted-foreground"}`}>{day?.getDate()}</span><div className="mt-1 space-y-1">{dayEvents.slice(0, 2).map(item => <div key={item.id} title={item.title} className="truncate rounded bg-primary/10 px-1.5 py-1 text-[10px] font-medium text-primary">{item.startsAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })} · {item.title}</div>)}</div></div>; })}</div></section>
    <section className="mt-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Compromissos deste mês</h2><Badge variant="secondary">{eventList?.length ?? 0} registros</Badge></div>{eventList?.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{eventList.map(item => <article key={item.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{new Intl.DateTimeFormat("pt-BR", { weekday: "short", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(item.startsAt)}</p></div><Badge variant="outline">{types[item.type]}</Badge></div><p className="mt-4 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" />{item.location || "Local a confirmar"}</p><p className="mt-1 text-xs text-muted-foreground">{item.neighborhood || "Bairro não informado"} · {item.region || "Região não informada"}</p>{canManage && <Button size="sm" variant="ghost" className="mt-3 -ml-2" onClick={() => { setEditingEventId(item.id); setForm({ title: item.title, type: item.type, startsAt: item.startsAt.toISOString().slice(0, 16), location: item.location || "", neighborhood: item.neighborhood || "", region: item.region || "", notes: item.notes || "" }); setOpenForm(true); }}>Editar compromisso</Button>}</article>)}</div> : <EmptyPanel title="Nenhum compromisso registrado neste mês" description="Os eventos criados pela equipe aparecerão no calendário e na lista operacional." action={canManage ? <Button onClick={() => setOpenForm(true)}><Plus className="mr-2 size-4" />Adicionar compromisso</Button> : undefined} />}</section>
  </>;
}
export default function Agenda() { return <CampaignGate><AgendaContent /></CampaignGate>; }
