import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, ClipboardCheck, FileKey2, Landmark, LockKeyhole, Scale, ShieldAlert, ShieldCheck, UserRoundCheck } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type RuleDraft = {
  blockBusinessDonation: boolean;
  requireExpenseDocument: boolean;
  reviewDeadlineHours: number;
  blockElectoralPhoneContact: boolean;
  requireConsentEvidence: boolean;
  requireHumanReviewForSyntheticContent: boolean;
  blockSyntheticPublicationWindow: boolean;
  requireResearchRegistrationForPublication: boolean;
  requireFinancialEvidence: boolean;
  ruleVersion: string;
};

const defaultRules: RuleDraft = { blockBusinessDonation: true, requireExpenseDocument: true, reviewDeadlineHours: 72, blockElectoralPhoneContact: true, requireConsentEvidence: true, requireHumanReviewForSyntheticContent: true, blockSyntheticPublicationWindow: true, requireResearchRegistrationForPublication: true, requireFinancialEvidence: true, ruleVersion: "2026.1" };
const decisionLabel: Record<string, string> = { approved: "Aprovado", blocked: "Bloqueado", needs_human_review: "Revisão humana", not_applicable: "Não aplicável" };
const reviewLabel: Record<string, string> = { pending: "Pendente", approved: "Aprovado", blocked: "Bloqueado", not_required: "Não exigida", cancelled: "Cancelada" };

function Metric({ label, value, icon: Icon, tone = "default" }: { label: string; value: number; icon: typeof ShieldCheck; tone?: "default" | "warn" | "danger" }) {
  const iconTone = tone === "danger" ? "text-destructive" : tone === "warn" ? "text-amber-600" : "text-primary";
  return <div className="rounded-2xl border bg-card p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm text-muted-foreground">{label}</span><Icon className={`size-4 ${iconTone}`} /></div><p className="mt-3 font-serif text-3xl font-semibold tabular-nums">{value}</p></div>;
}

function ComplianceCenterContent() {
  const { activeCampaign } = useCampaign();
  const campaignId = activeCampaign!.id;
  const canReview = activeCampaign?.memberRole === "admin";
  const overview = trpc.compliance.overview.useQuery({ campaignId });
  const sources = trpc.compliance.rules.sources.list.useQuery({ campaignId });
  const decisions = trpc.compliance.decisions.list.useQuery({ campaignId, limit: 100 });
  const dataSubjects = trpc.compliance.dataSubjects.list.useQuery({ campaignId });
  const utils = trpc.useUtils();
  const [rules, setRules] = useState<RuleDraft>(defaultRules);
  const [sourceForm, setSourceForm] = useState({ code: "", title: "", category: "norma", sourceUrl: "", sourceReference: "", summary: "" });
  const [requestForm, setRequestForm] = useState({ requestType: "access" as "access" | "correction" | "revocation" | "anonymization" | "deletion" | "portability" | "other", requesterReference: "", dueAt: "" });
  const [reviewNotes, setReviewNotes] = useState<Record<number, string>>({});

  useEffect(() => {
    const item = overview.data?.rules;
    if (!item) return;
    setRules({ blockBusinessDonation: item.blockBusinessDonation, requireExpenseDocument: item.requireExpenseDocument, reviewDeadlineHours: item.reviewDeadlineHours, blockElectoralPhoneContact: item.blockElectoralPhoneContact, requireConsentEvidence: item.requireConsentEvidence, requireHumanReviewForSyntheticContent: item.requireHumanReviewForSyntheticContent, blockSyntheticPublicationWindow: item.blockSyntheticPublicationWindow, requireResearchRegistrationForPublication: item.requireResearchRegistrationForPublication, requireFinancialEvidence: item.requireFinancialEvidence, ruleVersion: item.ruleVersion });
  }, [overview.data?.rules]);

  const refresh = () => { void utils.compliance.overview.invalidate({ campaignId }); void utils.compliance.decisions.list.invalidate({ campaignId, limit: 100 }); void utils.compliance.rules.sources.list.invalidate({ campaignId }); void utils.compliance.dataSubjects.list.invalidate({ campaignId }); };
  const updateRules = trpc.compliance.rules.update.useMutation({ onSuccess: () => { toast.success("Política de compliance atualizada."); refresh(); }, onError: error => toast.error(error.message) });
  const createSource = trpc.compliance.rules.sources.create.useMutation({ onSuccess: () => { toast.success("Fonte normativa registrada."); setSourceForm({ code: "", title: "", category: "norma", sourceUrl: "", sourceReference: "", summary: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const createRequest = trpc.compliance.dataSubjects.create.useMutation({ onSuccess: () => { toast.success("Solicitação LGPD registrada."); setRequestForm({ requestType: "access", requesterReference: "", dueAt: "" }); refresh(); }, onError: error => toast.error(error.message) });
  const reviewDecision = trpc.compliance.decisions.review.useMutation({ onSuccess: () => { toast.success("Decisão revisada e auditada."); refresh(); }, onError: error => toast.error(error.message) });
  const reviewContent = trpc.compliance.content.review.useMutation({ onSuccess: () => { toast.success("Conteúdo revisado."); refresh(); }, onError: error => toast.error(error.message) });
  const reviewSurvey = trpc.compliance.surveys.review.useMutation({ onSuccess: () => { toast.success("Pesquisa revisada."); refresh(); }, onError: error => toast.error(error.message) });
  const pendingDecisions = useMemo(() => (decisions.data ?? []).filter(item => item.reviewStatus === "pending"), [decisions.data]);

  if (activeCampaign?.memberRole === "partner") return <><PageHeader eyebrow="W9 Compliance Eleitoral" title="Controles de conformidade" description="Acesso disponível apenas para a coordenação responsável pela campanha." /><EmptyPanel title="Acesso restrito" description="Apenas administradores e coordenadores podem consultar controles, registros e revisões de compliance." /></>;

  const toggle = (key: keyof Omit<RuleDraft, "reviewDeadlineHours" | "ruleVersion">) => setRules(current => ({ ...current, [key]: !current[key] }));
  return <>
    <PageHeader eyebrow="W9 Compliance Eleitoral" title="Governança com decisão humana" description="Controles técnicos e evidências para organizar riscos de dados, comunicação, conteúdo, pesquisas e finanças. Não substitui revisão jurídica, contábil ou decisões da Justiça Eleitoral." />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
      <Metric label="Revisões pendentes" value={overview.data?.pendingReviews.length ?? 0} icon={ClipboardCheck} tone="warn" />
      <Metric label="Supressões ativas" value={overview.data?.suppressions.length ?? 0} icon={LockKeyhole} tone="danger" />
      <Metric label="IA pendente" value={overview.data?.syntheticContentsPending.length ?? 0} icon={ShieldAlert} tone="warn" />
      <Metric label="Pesquisas pendentes" value={overview.data?.publicSurveysPending.length ?? 0} icon={Landmark} tone="warn" />
      <Metric label="Evidências financeiras" value={overview.data?.financialEvidencePending.length ?? 0} icon={FileKey2} tone="warn" />
    </section>

    <section className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <div className="space-y-5">
        <section className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-serif text-2xl">Fila de revisão humana</h2><p className="mt-1 text-sm text-muted-foreground">Nenhuma pendência é liberada automaticamente. Toda decisão registra motivo, regra e responsável.</p></div><Badge variant="secondary">{pendingDecisions.length} pendente(s)</Badge></div><div className="mt-4 space-y-3">{pendingDecisions.length ? pendingDecisions.map(item => <div key={item.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{item.action}</p><p className="text-xs text-muted-foreground">{item.entityType} #{item.entityId ?? "—"} · regra {item.ruleVersion}</p></div><Badge variant="outline">{decisionLabel[item.decision] ?? item.decision}</Badge></div><ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-muted-foreground">{item.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>{canReview && <div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input aria-label={`Justificativa da decisão ${item.id}`} value={reviewNotes[item.id] ?? ""} onChange={event => setReviewNotes(current => ({ ...current, [item.id]: event.target.value }))} placeholder="Justificativa da revisão (recomendado)" /><Button size="sm" onClick={() => reviewDecision.mutate({ decisionId: item.id, status: "approved", note: reviewNotes[item.id] || undefined })} disabled={reviewDecision.isPending}><CheckCircle2 className="mr-1.5 size-4" />Aprovar</Button><Button size="sm" variant="destructive" onClick={() => reviewDecision.mutate({ decisionId: item.id, status: "blocked", note: reviewNotes[item.id] || undefined })} disabled={reviewDecision.isPending}>Bloquear</Button></div>}</div>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Não há decisões pendentes nesta campanha.</p>}</div></section>

        <section className="rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-serif text-2xl">Objetos pendentes</h2><p className="mt-1 text-sm text-muted-foreground">Conteúdos sintéticos, pesquisas públicas e lançamentos sem evidência aguardam a conferência responsável.</p></div><ShieldCheck className="size-5 text-primary" /></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-muted/55 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Conteúdo sintético</p>{overview.data?.syntheticContentsPending.length ? overview.data.syntheticContentsPending.map(item => <div key={item.id} className="mt-2 text-sm"><p className="font-medium">{item.title}</p>{canReview && <div className="mt-2 flex gap-2"><Button size="sm" onClick={() => reviewContent.mutate({ contentId: item.id, status: "approved" })}>Aprovar</Button><Button size="sm" variant="outline" onClick={() => reviewContent.mutate({ contentId: item.id, status: "blocked" })}>Bloquear</Button></div>}</div>) : <p className="mt-2 text-sm text-muted-foreground">Nenhum pendente.</p>}</div><div className="rounded-xl bg-muted/55 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Pesquisa pública</p>{overview.data?.publicSurveysPending.length ? overview.data.publicSurveysPending.map(item => <div key={item.id} className="mt-2 text-sm"><p className="font-medium">{item.title}</p>{canReview && <div className="mt-2 flex gap-2"><Button size="sm" onClick={() => reviewSurvey.mutate({ surveyId: item.id, status: "approved" })}>Aprovar</Button><Button size="sm" variant="outline" onClick={() => reviewSurvey.mutate({ surveyId: item.id, status: "blocked" })}>Bloquear</Button></div>}</div>) : <p className="mt-2 text-sm text-muted-foreground">Nenhuma pendente.</p>}</div><div className="rounded-xl bg-muted/55 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Financeiro</p>{overview.data?.financialEvidencePending.length ? overview.data.financialEvidencePending.map(item => <div key={item.id} className="mt-2 text-sm"><p className="font-medium">{item.category} · {item.counterpartyName}</p><p className="text-xs text-muted-foreground">{item.evidenceStatus === "pending" ? "Sem evidência" : "Revisão pendente"}</p></div>) : <p className="mt-2 text-sm text-muted-foreground">Nenhum pendente.</p>}</div></div></section>

        <section className="rounded-2xl border bg-card p-5"><h2 className="font-serif text-2xl">Histórico de decisões</h2><div className="mt-4 divide-y rounded-xl border">{decisions.data?.length ? decisions.data.slice(0, 10).map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="text-sm font-medium">{item.action}</p><p className="text-xs text-muted-foreground">{item.reasons[0] || "Sem motivo registrado"}</p></div><div className="text-right"><Badge variant={item.decision === "blocked" ? "destructive" : "outline"}>{reviewLabel[item.reviewStatus] ?? item.reviewStatus}</Badge><p className="mt-1 text-[11px] text-muted-foreground">{new Date(item.createdAt).toLocaleString("pt-BR")}</p></div></div>) : <p className="p-5 text-sm text-muted-foreground">Ainda não há decisões registradas.</p>}</div></section>
        <section className="rounded-2xl border bg-card p-5"><h2 className="font-serif text-2xl">Ledger de consentimento</h2><p className="mt-1 text-sm text-muted-foreground">Registro cronológico de concessões, revogações e alterações de finalidade. A identificação do contato não é exibida neste painel.</p><div className="mt-4 divide-y rounded-xl border">{overview.data?.recentConsentLedger.length ? overview.data.recentConsentLedger.slice(0, 8).map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="text-sm font-medium">{item.status === "granted" ? "Autorização registrada" : item.status === "revoked" ? "Autorização revogada" : item.status === "expired" ? "Autorização expirada" : "Importação sem autorização"}</p><p className="text-xs text-muted-foreground">{item.channel} · {item.purpose}</p></div><p className="text-xs text-muted-foreground">{new Date(item.occurredAt).toLocaleString("pt-BR")}</p></div>) : <p className="p-5 text-sm text-muted-foreground">Nenhum evento de consentimento registrado.</p>}</div></section>
      </div>

      <div className="space-y-5">
        <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><Scale className="size-5 text-primary" /><h2 className="font-serif text-2xl">Política da campanha</h2></div><p className="mt-1 text-sm text-muted-foreground">A versão é registrada com as decisões. Altere somente após validação responsável.</p><div className="mt-4 space-y-3">{([ ["blockElectoralPhoneContact", "Bloquear contato eleitoral por telefone"], ["requireConsentEvidence", "Exigir evidência ativa de consentimento"], ["requireHumanReviewForSyntheticContent", "Revisar conteúdo sintético antes de publicar"], ["blockSyntheticPublicationWindow", "Bloquear janela restrita para conteúdo sintético"], ["requireResearchRegistrationForPublication", "Exigir registro para pesquisa pública"], ["blockBusinessDonation", "Bloquear receita identificada por CNPJ"], ["requireExpenseDocument", "Exigir documento ou recibo de despesa"], ["requireFinancialEvidence", "Revisar evidência financeira"], ] as Array<[keyof Omit<RuleDraft, "reviewDeadlineHours" | "ruleVersion">, string]>).map(([key, label]) => <label key={key} className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" className="mt-1 size-4 accent-primary" checked={rules[key]} onChange={() => toggle(key)} disabled={!canReview} /><span>{label}</span></label>)}</div><div className="mt-4 grid grid-cols-2 gap-3"><div><Label htmlFor="rule-version">Versão</Label><Input id="rule-version" value={rules.ruleVersion} onChange={event => setRules(current => ({ ...current, ruleVersion: event.target.value }))} disabled={!canReview} /></div><div><Label htmlFor="review-hours">Prazo de revisão</Label><Input id="review-hours" type="number" min={1} max={720} value={rules.reviewDeadlineHours} onChange={event => setRules(current => ({ ...current, reviewDeadlineHours: Number(event.target.value) || 1 }))} disabled={!canReview} /></div></div>{canReview && <Button className="mt-4 w-full" onClick={() => updateRules.mutate({ campaignId, ...rules })} disabled={updateRules.isPending}>Salvar política versionada</Button>}</section>

        <section className="rounded-2xl border bg-card p-5"><h2 className="font-serif text-2xl">Fontes e vigência</h2><p className="mt-1 text-sm text-muted-foreground">Registre a fonte consultada; o sistema não interpreta normas nem substitui especialistas.</p>{canReview && <form className="mt-4 space-y-3" onSubmit={(event: FormEvent) => { event.preventDefault(); createSource.mutate({ campaignId, ...sourceForm, sourceReference: sourceForm.sourceReference || undefined, summary: sourceForm.summary || undefined }); }}><Input required placeholder="Código interno da fonte" value={sourceForm.code} onChange={event => setSourceForm(current => ({ ...current, code: event.target.value }))} /><Input required placeholder="Título da fonte" value={sourceForm.title} onChange={event => setSourceForm(current => ({ ...current, title: event.target.value }))} /><Input required placeholder="URL oficial da fonte" type="url" value={sourceForm.sourceUrl} onChange={event => setSourceForm(current => ({ ...current, sourceUrl: event.target.value }))} /><Button type="submit" variant="outline" className="w-full" disabled={createSource.isPending}>Registrar fonte</Button></form>}<div className="mt-4 space-y-2">{sources.data?.length ? sources.data.map(item => <a key={item.id} href={item.sourceUrl} target="_blank" rel="noreferrer" className="block rounded-lg border p-3 text-sm hover:bg-muted/50"><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.category} · versão {item.version}</p></a>) : <p className="text-sm text-muted-foreground">Nenhuma fonte registrada para esta campanha.</p>}</div></section>

        <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><UserRoundCheck className="size-5 text-primary" /><h2 className="font-serif text-2xl">Solicitações LGPD</h2></div><p className="mt-1 text-sm text-muted-foreground">O identificador é protegido por hash; não inclua conteúdo sensível nas anotações.</p>{canReview && <form className="mt-4 space-y-3" onSubmit={(event: FormEvent) => { event.preventDefault(); createRequest.mutate({ campaignId, requestType: requestForm.requestType, requesterReference: requestForm.requesterReference, dueAt: requestForm.dueAt ? new Date(`${requestForm.dueAt}T12:00:00`) : undefined }); }}><select value={requestForm.requestType} onChange={event => setRequestForm(current => ({ ...current, requestType: event.target.value as typeof requestForm.requestType }))} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="access">Acesso a dados</option><option value="correction">Correção</option><option value="revocation">Revogação</option><option value="anonymization">Anonimização</option><option value="deletion">Eliminação</option><option value="portability">Portabilidade</option><option value="other">Outra</option></select><Input required placeholder="Referência do solicitante" value={requestForm.requesterReference} onChange={event => setRequestForm(current => ({ ...current, requesterReference: event.target.value }))} /><Input type="date" value={requestForm.dueAt} onChange={event => setRequestForm(current => ({ ...current, dueAt: event.target.value }))} /><Button type="submit" variant="outline" className="w-full" disabled={createRequest.isPending}>Registrar solicitação</Button></form>}<div className="mt-4 space-y-2">{dataSubjects.data?.length ? dataSubjects.data.slice(0, 5).map(item => <div key={item.id} className="rounded-lg border p-3 text-sm"><p className="font-medium">{item.requestType}</p><p className="text-xs text-muted-foreground">{item.status} · {new Date(item.createdAt).toLocaleDateString("pt-BR")}</p></div>) : <p className="text-sm text-muted-foreground">Nenhuma solicitação registrada.</p>}</div></section>
      </div>
    </section>
    <p className="mt-6 flex items-start gap-2 rounded-xl border border-amber-500/30 bg-amber-50/60 p-4 text-sm text-amber-950 dark:bg-amber-950/20 dark:text-amber-100"><AlertTriangle className="mt-0.5 size-4 shrink-0" />Os controles do W9 reduzem riscos operacionais e mantêm evidências. Antes de publicidade, pesquisa divulgada, prestação oficial ou resposta a titulares de dados, realize a revisão jurídica e contábil adequada.</p>
  </>;
}

export default function ComplianceCenter() { return <CampaignGate><ComplianceCenterContent /></CampaignGate>; }
