import { EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { ShieldCheck, Undo2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function ConsentCenter() {
  const { activeCampaign } = useCampaign(); const utils = trpc.useUtils(); const [voterId, setVoterId] = useState(""); const [purpose, setPurpose] = useState("Comunicação e relacionamento de campanha"); const [source, setSource] = useState("Registro de campo"); const [evidence, setEvidence] = useState(""); const [expiresAt, setExpiresAt] = useState("");
  const voters = trpc.voters.list.useQuery({ campaignId: activeCampaign?.id ?? 0 }, { enabled: Boolean(activeCampaign) });
  const records = trpc.consent.list.useQuery({ voterId: Number(voterId) }, { enabled: Boolean(voterId) });
  const create = trpc.consent.create.useMutation({ onSuccess: async () => { await utils.consent.list.invalidate(); toast.success("Consentimento registrado com evidência."); setEvidence(""); }, onError: error => toast.error(error.message) });
  const revoke = trpc.consent.revoke.useMutation({ onSuccess: async () => { await utils.consent.list.invalidate(); toast.success("Consentimento revogado e contato bloqueado quando não houver outra base ativa."); }, onError: error => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (!voterId) return toast.error("Selecione um contato."); create.mutate({ voterId: Number(voterId), purpose, source, evidence: evidence || undefined, consentedAt: new Date(), expiresAt: expiresAt ? new Date(`${expiresAt}T23:59:59`) : undefined }); };
  if (!activeCampaign) return <EmptyPanel title="Selecione uma campanha" description="A base legal é acompanhada por campanha e organização." />;
  return <section><PageHeader eyebrow="Proteção de dados" title="Central de consentimento" description="Registre a finalidade, a origem e a evidência da autorização do contato. Revogações são preservadas no histórico." />
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><form onSubmit={submit} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-5 flex gap-3"><span className="rounded-xl bg-emerald-50 p-2 text-emerald-700"><ShieldCheck className="size-5" /></span><div><h2 className="font-semibold">Novo consentimento</h2><p className="text-sm text-muted-foreground">Utilize somente uma base legítima e informe a origem do registro.</p></div></div><div className="space-y-4"><div className="space-y-2"><Label htmlFor="consent-voter">Contato</Label><select id="consent-voter" value={voterId} onChange={event => setVoterId(event.target.value)} className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Selecione</option>{(voters.data ?? []).map(voter => <option key={voter.id} value={voter.id}>{voter.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="consent-purpose">Finalidade</Label><Input id="consent-purpose" value={purpose} onChange={event => setPurpose(event.target.value)} required /></div><div className="space-y-2"><Label htmlFor="consent-source">Origem</Label><Input id="consent-source" value={source} onChange={event => setSource(event.target.value)} required /></div><div className="space-y-2"><Label htmlFor="consent-expires">Validade</Label><Input id="consent-expires" type="date" value={expiresAt} onChange={event => setExpiresAt(event.target.value)} /><p className="text-xs text-muted-foreground">Opcional. Sem data, a autorização permanece ativa até revogação.</p></div><div className="space-y-2"><Label htmlFor="consent-evidence">Evidência</Label><Textarea id="consent-evidence" value={evidence} onChange={event => setEvidence(event.target.value)} placeholder="Ex.: autorização verbal registrada em visita, formulário assinado ou QR Code." /></div><Button type="submit" className="w-full" disabled={create.isPending}>Registrar consentimento</Button></div></form>
      <div className="rounded-2xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Histórico do contato</h2><p className="text-sm text-muted-foreground">Selecione um contato para consultar ou revogar registros.</p></div><div className="divide-y">{!voterId && <p className="p-6 text-sm text-muted-foreground">Nenhum contato selecionado.</p>}{(records.data ?? []).map(record => <div className="p-4" key={record.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{record.purpose}</p><p className="mt-1 text-sm text-muted-foreground">{record.source} · {new Date(record.consentedAt).toLocaleString("pt-BR")}</p><p className="mt-1 text-xs text-muted-foreground">{record.evidence || "Sem evidência descritiva"}</p>{record.expiresAt && <p className="mt-1 text-xs font-medium text-amber-700">Válido até {new Date(record.expiresAt).toLocaleDateString("pt-BR")}</p>}</div><div className="text-right"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${record.status === "active" ? "bg-emerald-100 text-emerald-800" : "bg-muted text-muted-foreground"}`}>{record.status}</span>{record.status === "active" && <Button variant="ghost" size="sm" className="mt-2 text-destructive" onClick={() => revoke.mutate({ consentId: record.id })}><Undo2 className="mr-1 size-3" />Revogar</Button>}</div></div></div>)}</div></div></div></section>;
}
