import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { BookOpenText, CheckCircle2, ExternalLink, Plus, Send } from "lucide-react";
import { FormEvent, useState } from "react";

const channelLabels = { social: "Redes sociais", whatsapp: "WhatsApp", print: "Impresso", speech: "Discurso", video: "Vídeo", other: "Outro" } as const;
const statusLabels = { draft: "Rascunho", review: "Em revisão", approved: "Aprovado", archived: "Arquivado" } as const;

function ContentsContent() {
  const { activeCampaign } = useCampaign();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ title: "", body: "", assetUrl: "", version: 1, channel: "social" as keyof typeof channelLabels, status: "draft" as keyof typeof statusLabels });
  const { data, isLoading, refetch } = trpc.contents.list.useQuery({ campaignId: activeCampaign!.id });
  const create = trpc.contents.create.useMutation({ onSuccess: () => { setForm({ title: "", body: "", assetUrl: "", version: 1, channel: "social", status: "draft" }); setOpen(false); void refetch(); } });
  const update = trpc.contents.update.useMutation({ onSuccess: () => void refetch() });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ campaignId: activeCampaign!.id, ...form, assetUrl: form.assetUrl || undefined }); };
  if (isLoading) return <div className="h-80 animate-pulse rounded-2xl bg-muted" />;
  return <><PageHeader eyebrow="Comunicação" title="Biblioteca de conteúdos" description="Centralize textos, roteiros e materiais em uma única fonte de verdade, com revisão e aprovação claras." action={<Button onClick={() => setOpen(value => !value)} className="bg-[#103527] text-white hover:bg-[#174a35]"><Plus className="mr-2 size-4" />Novo conteúdo</Button>} />
    {open && <form onSubmit={submit} className="mb-6 grid gap-4 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 md:grid-cols-2"><div className="space-y-2"><label className="text-sm font-medium">Título</label><Input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Ex.: Convite para reunião de bairro" /></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><label className="text-sm font-medium">Canal</label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.channel} onChange={event => setForm({ ...form, channel: event.target.value as typeof form.channel })}>{Object.entries(channelLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><div className="space-y-2"><label className="text-sm font-medium">Status</label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.status} onChange={event => setForm({ ...form, status: event.target.value as typeof form.status })}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></div><div className="space-y-2"><label className="text-sm font-medium">Link do material</label><Input type="url" value={form.assetUrl} onChange={event => setForm({ ...form, assetUrl: event.target.value })} placeholder="https://..." /></div><div className="space-y-2"><label className="text-sm font-medium">Versão</label><Input type="number" min={1} value={form.version} onChange={event => setForm({ ...form, version: Number(event.target.value) || 1 })} /></div><div className="space-y-2 md:col-span-2"><label className="text-sm font-medium">Conteúdo</label><Textarea required className="min-h-36" value={form.body} onChange={event => setForm({ ...form, body: event.target.value })} placeholder="Escreva o texto ou roteiro a ser revisado." /></div><div className="flex gap-2 md:col-span-2"><Button type="submit" disabled={create.isPending}>{create.isPending ? "Salvando..." : "Salvar conteúdo"}</Button><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancelar</Button></div></form>}
    {data?.length ? <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{data.map(item => <article key={item.id} className="flex min-h-56 flex-col rounded-2xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><Badge variant="outline">{channelLabels[item.channel]} · v{item.version}</Badge><Badge variant={item.status === "approved" ? "default" : "secondary"}>{statusLabels[item.status]}</Badge></div><h2 className="mt-4 font-serif text-xl">{item.title}</h2><p className="mt-3 line-clamp-4 text-sm leading-6 text-muted-foreground">{item.body}</p>{item.assetUrl ? <a href={item.assetUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline"><ExternalLink className="size-3" />Abrir material vinculado</a> : null}<div className="mt-auto pt-5">{item.status !== "approved" ? <Button size="sm" variant="outline" disabled={update.isPending} onClick={() => update.mutate({ id: item.id, title: item.title, body: item.body, assetUrl: item.assetUrl ?? undefined, version: item.version, channel: item.channel, status: "approved" })}><CheckCircle2 className="mr-2 size-4" />Aprovar conteúdo</Button> : <span className="inline-flex items-center gap-2 text-xs font-medium text-primary"><Send className="size-4" />Material aprovado</span>}</div></article>)}</div> : <EmptyPanel title="A biblioteca ainda está vazia" description="Registre os primeiros textos, roteiros e links de materiais para organizar as versões aprovadas da campanha." action={<span className="inline-flex items-center gap-2 text-sm font-medium text-primary"><BookOpenText className="size-4" />Comece por um conteúdo</span>} />}
  </>;
}
export default function Contents() { return <CampaignGate><ContentsContent /></CampaignGate>; }
