import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CalendarDays, CheckSquare, ClipboardList, FileText, MapPinned, Printer, UsersRound } from "lucide-react";

const dateTime = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });

function DailyCoordinationContent() {
  const { activeCampaign } = useCampaign(); const campaignId = activeCampaign!.id;
  const report = trpc.dashboard.dailyCoordination.useQuery({ campaignId });
  if (report.isLoading) return <div className="h-80 animate-pulse rounded-2xl bg-muted" />;
  if (report.isError || !report.data) return <EmptyPanel title="Relatório restrito" description="O relatório diário está disponível para perfis de coordenação desta campanha." />;
  const data = report.data; const daily = data.daily;
  return <section><PageHeader eyebrow="Prioridades da campanha" title="Relatório diário de coordenação" description={`Leitura consolidada em ${new Intl.DateTimeFormat("pt-BR", { dateStyle: "full", timeStyle: "short" }).format(data.generatedAt)}.`} action={<Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 size-4" />Imprimir / PDF</Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={CheckSquare} label="Tarefas vencidas" value={daily.overdue.length} tone={daily.overdue.length ? "text-rose-700" : "text-primary"} /><Metric icon={UsersRound} label="Voluntários ativos" value={data.metrics.activeVolunteers} /><Metric icon={ClipboardList} label="Demandas abertas" value={data.metrics.openDemands} tone={data.metrics.overdueDemands ? "text-amber-700" : "text-primary"} /><Metric icon={MapPinned} label="Ações de rua hoje" value={data.metrics.todayStreetActions} /></div>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Panel icon={AlertTriangle} title="Alertas que pedem decisão" description="Prazos, metas e demandas que requerem acompanhamento."><AlertList title="Tarefas vencidas" rows={daily.overdue.map(item => ({ id: item.task.id, title: item.task.title, detail: item.assignee?.name || "Sem responsável" }))} empty="Nenhuma tarefa vencida." /><AlertList title="Metas em atenção" rows={data.attentionGoals.map(item => ({ id: item.id, title: item.title, detail: `${item.currentValue}/${item.targetValue} ${item.unit}` }))} empty="Nenhuma meta em atenção." /><AlertList title="Demandas vencidas" rows={data.overdueDemands.map(item => ({ id: item.demand.id, title: `${item.demand.protocol} · ${item.demand.title}`, detail: item.assignee?.name || "Sem responsável" }))} empty="Nenhuma demanda vencida." /></Panel><Panel icon={CalendarDays} title="Agenda e execução de hoje" description="Compromissos e ações territoriais programadas."><AlertList title="Eventos" rows={daily.todayEvents.map(item => ({ id: item.id, title: item.title, detail: dateTime.format(item.startsAt) }))} empty="Nenhum evento previsto para hoje." /><AlertList title="Ações de rua" rows={data.todayStreetActions.map(item => ({ id: item.action.id, title: item.action.title, detail: item.action.territory || item.action.neighborhood || "Território a definir" }))} empty="Nenhuma ação de rua prevista para hoje." /><AlertList title="Próximas tarefas" rows={daily.dueToday.map(item => ({ id: item.task.id, title: item.task.title, detail: item.assignee?.name || "Sem responsável" }))} empty="Nenhuma tarefa para hoje." /></Panel></section>
    <section className="mt-6 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><MapPinned className="size-5" /></span><div><h2 className="font-semibold">Cobertura territorial programada</h2><p className="text-xs text-muted-foreground">Baseada em escalas futuras e confirmações de equipe.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.territoryCoverage.map(item => <article key={item.territory} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{item.territory}</p><p className="mt-1 text-xs text-muted-foreground">{item.shifts} escala(s) · {item.confirmed}/{item.assigned} confirmações</p></div><Badge variant={item.coverageRate < 60 ? "destructive" : "secondary"}>{item.coverageRate}%</Badge></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-muted"><div className={item.coverageRate < 60 ? "h-full bg-rose-600" : "h-full bg-primary"} style={{ width: `${item.coverageRate}%` }} /></div></article>)}{!data.territoryCoverage.length && <p className="rounded-xl bg-muted/50 p-4 text-sm text-muted-foreground">Nenhuma escala futura para calcular cobertura territorial.</p>}</div></section>
    <section className="mt-6 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><FileText className="size-5" /></span><div><h2 className="font-semibold">Encaminhamentos abertos</h2><p className="text-xs text-muted-foreground">Demandas que permanecem no fluxo de resposta e devolutiva.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{data.openDemands.map(item => <article key={item.demand.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-primary">{item.demand.protocol}</p><h3 className="mt-1 font-medium">{item.demand.title}</h3><p className="mt-1 text-xs text-muted-foreground">{item.demand.category} · {item.assignee?.name || "Sem responsável"}</p></div><Badge variant={item.demand.status === "waiting_response" ? "secondary" : "outline"}>{item.demand.status.replaceAll("_", " ")}</Badge></div></article>)}{!data.openDemands.length && <p className="rounded-xl bg-muted/50 p-4 text-sm text-muted-foreground">Nenhuma demanda aberta no momento.</p>}</div></section>
  </section>;
}
function Panel({ icon: Icon, title, description, children }: { icon: typeof AlertTriangle; title: string; description: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><Icon className="size-5" /></span><div><h2 className="font-semibold">{title}</h2><p className="text-xs text-muted-foreground">{description}</p></div></div><div className="mt-5 space-y-5">{children}</div></section>; }
function AlertList({ title, rows, empty }: { title: string; rows: Array<{ id: number; title: string; detail: string }>; empty: string }) { return <div><h3 className="text-sm font-semibold">{title}</h3><div className="mt-2 space-y-2">{rows.map(item => <div key={item.id} className="rounded-xl bg-muted/55 p-3"><p className="text-sm font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.detail}</p></div>)}{!rows.length && <p className="rounded-xl bg-muted/30 p-3 text-sm text-muted-foreground">{empty}</p>}</div></div>; }
function Metric({ icon: Icon, label, value, tone = "text-primary" }: { icon: typeof CheckSquare; label: string; value: number; tone?: string }) { return <div className="rounded-2xl border bg-card p-5 shadow-sm"><Icon className={`size-5 ${tone}`} /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-serif text-3xl">{value}</p></div>; }
export default function DailyCoordination() { return <CampaignGate><DailyCoordinationContent /></CampaignGate>; }
