import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { MetricCard } from "@/components/MetricCard";
import { Badge } from "@/components/ui/badge";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { Activity, CalendarDays, CheckSquare, CircleAlert, ContactRound, Flag, MapPin } from "lucide-react";

const dateFormat = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });

function DashboardContent() {
  const { activeCampaign } = useCampaign();
  const { data, isLoading } = trpc.dashboard.summary.useQuery({ campaignId: activeCampaign!.id });
  if (isLoading) return <div className="space-y-6"><PageHeader eyebrow="Visão geral" title="Painel de comando" description="Indicadores, agenda e acompanhamento tático em um só lugar." /><div className="h-64 animate-pulse rounded-2xl bg-muted" /></div>;
  const metrics = data?.metrics ?? { tasks: 0, voters: 0, goals: 0, incidents: 0 };
  return <>
    <PageHeader eyebrow="Visão geral" title="Painel de comando" description={`Acompanhe o ritmo operacional de ${activeCampaign?.name} com visibilidade e foco nas próximas entregas.`} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Tarefas em operação" value={metrics.tasks} supporting="Atividades registradas" icon={CheckSquare} /><MetricCard label="Contatos cadastrados" value={metrics.voters} supporting="Base consentida e segmentável" icon={ContactRound} tone="gold" /><MetricCard label="Metas acompanhadas" value={metrics.goals} supporting="Objetivos da campanha" icon={Flag} tone="slate" /><MetricCard label="Ocorrências de campo" value={metrics.incidents} supporting="Registros para acompanhamento" icon={CircleAlert} tone="rose" /></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-2xl border border-border/75 bg-card p-5 shadow-[0_12px_28px_-24px_rgba(0,0,0,.6)]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Próximos compromissos</p><p className="mt-1 text-xs text-muted-foreground">Agenda confirmada da campanha</p></div><CalendarDays className="size-5 text-primary" /></div>{data?.upcomingEvents.length ? <div className="mt-5 divide-y divide-border/70">{data.upcomingEvents.map(event => <div key={event.id} className="flex items-center gap-4 py-4 first:pt-0 last:pb-0"><div className="flex size-11 shrink-0 flex-col items-center justify-center rounded-xl bg-primary/10 text-primary"><span className="text-[10px] font-bold uppercase">{new Intl.DateTimeFormat("pt-BR", { month: "short" }).format(event.startsAt)}</span><span className="text-sm font-bold leading-none">{event.startsAt.getDate()}</span></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{event.title}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" />{event.location || "Local a confirmar"} · {dateFormat.format(event.startsAt)}</p></div><Badge variant="outline" className="capitalize">{event.type}</Badge></div>)}</div> : <EmptyPanel title="Nenhum compromisso futuro" description="Os eventos registrados na agenda aparecerão aqui, organizados por data e horário." />}</section>
      <section className="rounded-2xl border border-border/75 bg-[#103527] p-5 text-white shadow-[0_16px_35px_-24px_rgba(0,0,0,.75)]"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Pulso de indicadores</p><p className="mt-1 text-xs text-white/60">Atualizações estratégicas</p></div><Activity className="size-5 text-[#e4cc8d]" /></div>{data?.indicators.length ? <div className="mt-6 space-y-5">{data.indicators.map(indicator => { const progress = indicator.targetValue ? Math.min(100, Math.round((indicator.currentValue / indicator.targetValue) * 100)) : 0; return <div key={indicator.id}><div className="flex justify-between text-xs"><span className="text-white/75">{indicator.label}</span><span className="font-semibold">{indicator.currentValue}/{indicator.targetValue} {indicator.unit}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#e4cc8d]" style={{ width: `${progress}%` }} /></div></div>; })}</div> : <div className="mt-6 rounded-xl border border-white/10 bg-white/5 p-5 text-sm leading-6 text-white/65">Cadastre os primeiros indicadores no módulo de monitoramento para visualizar a evolução estratégica neste painel.</div>}</section>
    </div>
    <section className="mt-6 rounded-2xl border border-border/75 bg-card p-5"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold">Atividade de campo</p><p className="mt-1 text-xs text-muted-foreground">Ocorrências e feedbacks mais recentes</p></div><CircleAlert className="size-5 text-primary" /></div>{data?.recentIncidents.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.recentIncidents.map(item => <article key={item.id} className="rounded-xl bg-muted/60 p-4"><div className="flex items-start justify-between gap-3"><p className="font-medium">{item.title}</p><Badge variant="secondary" className="capitalize">{item.status}</Badge></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.description}</p></article>)}</div> : <EmptyPanel title="Nenhuma ocorrência registrada" description="Feedbacks e ocorrências de campo surgirão aqui à medida que a operação for registrando informações." />}</section>
  </>;
}

export default function Dashboard() { return <CampaignGate><DashboardContent /></CampaignGate>; }
