import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CampaignGate, PageHeader } from "@/components/CampaignShell";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { BarChart3, CalendarDays, CheckCircle2, MapPin, Star, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

function Metric({ icon: Icon, label, value, description }: { icon: typeof CalendarDays; label: string; value: string | number; description: string }) { return <article className="rounded-2xl border bg-card p-5 shadow-sm"><Icon className="size-5 text-primary" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-serif text-3xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></article>; }
function TerritoryBars({ title, items }: { title: string; items: Array<{ label: string; events: number; registrations: number; checkedIn: number; attendanceRate: number; averageRating: number | null }> }) { const max = Math.max(1, ...items.map(item => item.checkedIn)); return <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><MapPin className="size-5 text-primary" /><div><h2 className="font-serif text-xl">{title}</h2><p className="text-xs text-muted-foreground">Presença confirmada, inscrições e taxa de comparecimento.</p></div></div><div className="mt-5 space-y-3">{items.slice(0, 10).map(item => <article key={item.label} className="rounded-xl border border-border/70 p-3"><div className="flex items-center justify-between gap-3"><span className="text-sm font-semibold">{item.label}</span><Badge variant="outline">{item.attendanceRate}% presença</Badge></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[#c9a85b]" style={{ width: `${Math.round((item.checkedIn / max) * 100)}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{item.events} evento(s) · {item.registrations} inscrições · {item.checkedIn} presença(s){item.averageRating ? ` · nota ${item.averageRating}` : ""}</p></article>)}{!items.length && <p className="rounded-xl bg-muted/50 p-4 text-sm text-muted-foreground">Nenhum evento no recorte selecionado.</p>}</div></section>; }
function EventIndicatorsContent() {
  const { activeCampaign } = useCampaign();
  const [neighborhood, setNeighborhood] = useState(""); const [region, setRegion] = useState("");
  const [startsAt, setStartsAt] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [endsAt, setEndsAt] = useState(() => new Date());
  const input = useMemo(() => ({ campaignId: activeCampaign!.id, startsAt, endsAt: new Date(`${endsAt.toISOString().slice(0, 10)}T23:59:59`), neighborhood: neighborhood || undefined, region: region || undefined }), [activeCampaign, startsAt, endsAt, neighborhood, region]);
  const indicators = trpc.planning.indicators.useQuery(input); const data = indicators.data;
  return <section><PageHeader eyebrow="Mobilização e participação" title="Indicadores de eventos" description="Acompanhe inscrições, presenças e retorno pós-evento por território, sem expor dados individuais." />
    <section className="mt-5 rounded-2xl border bg-card p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-4"><label className="text-xs font-semibold text-muted-foreground">Início<input aria-label="Início dos indicadores" type="date" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground" value={startsAt.toISOString().slice(0, 10)} onChange={event => setStartsAt(new Date(`${event.target.value}T00:00:00`))} /></label><label className="text-xs font-semibold text-muted-foreground">Fim<input aria-label="Fim dos indicadores" type="date" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground" value={endsAt.toISOString().slice(0, 10)} onChange={event => setEndsAt(new Date(`${event.target.value}T00:00:00`))} /></label><label className="text-xs font-semibold text-muted-foreground">Bairro<input aria-label="Filtrar indicadores por bairro" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground" value={neighborhood} onChange={event => setNeighborhood(event.target.value)} placeholder="Todos" /></label><label className="text-xs font-semibold text-muted-foreground">Região<input aria-label="Filtrar indicadores por região" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm text-foreground" value={region} onChange={event => setRegion(event.target.value)} placeholder="Todas" /></label></div><div className="mt-3 flex justify-end"><Button size="sm" variant="outline" onClick={() => { setNeighborhood(""); setRegion(""); setStartsAt(new Date(new Date().getFullYear(), new Date().getMonth(), 1)); setEndsAt(new Date()); }}>Limpar filtros</Button></div></section>
    {indicators.isLoading ? <div className="mt-6 h-64 animate-pulse rounded-2xl bg-muted" /> : indicators.isError ? <div className="mt-6 rounded-2xl border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive">Não foi possível carregar os indicadores. <Button size="sm" variant="outline" className="ml-2" onClick={() => void indicators.refetch()}>Tentar novamente</Button></div> : <><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={CalendarDays} label="Eventos" value={data?.summary.totalEvents ?? 0} description="No período e filtros" /><Metric icon={UsersRound} label="Inscrições" value={data?.summary.registrations ?? 0} description="Participantes registrados" /><Metric icon={CheckCircle2} label="Presenças" value={data?.summary.checkedIn ?? 0} description="Check-ins confirmados" /><Metric icon={BarChart3} label="Comparecimento" value={`${data?.summary.attendanceRate ?? 0}%`} description="Presenças / inscrições" /><Metric icon={Star} label="Avaliação média" value={data?.summary.averageRating ?? "—"} description={`${data?.summary.feedbackCount ?? 0} retorno(s) recebidos`} /></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><TerritoryBars title="Por região" items={data?.byRegion ?? []} /><TerritoryBars title="Por bairro" items={data?.byNeighborhood ?? []} /></div><section className="mt-6 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><BarChart3 className="size-5 text-primary" /><div><h2 className="font-serif text-xl">Formatos de evento</h2><p className="text-xs text-muted-foreground">Distribuição operacional por tipo de agenda.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(data?.byType ?? []).map(item => <article key={item.label} className="rounded-xl bg-muted/45 p-4"><p className="text-sm font-semibold">{item.label}</p><p className="mt-2 font-serif text-2xl">{item.events}</p><p className="text-xs text-muted-foreground">{item.checkedIn} presença(s) · {item.attendanceRate}% comparecimento</p></article>)}{!data?.byType.length && <p className="col-span-full rounded-xl bg-muted/50 p-4 text-sm text-muted-foreground">Ainda não há eventos no recorte selecionado.</p>}</div></section></>}</section>;
}
export default function EventIndicators() { return <CampaignGate><EventIndicatorsContent /></CampaignGate>; }
