import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Chrome, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function Login() {
  const [, navigate] = useLocation(); const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const login = trpc.auth.login.useMutation({ onSuccess: () => navigate("/") }); const register = trpc.auth.register.useMutation({ onSuccess: () => navigate("/onboarding") }); const action = mode === "login" ? login : register;
  return <main className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><section className="w-full max-w-md rounded-[2rem] border border-[#dbe5df] bg-white p-8 shadow-[0_30px_90px_-50px_rgba(16,53,39,.55)]"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#103527] text-[#e4cc8d]"><ShieldCheck className="size-6" /></div><h1 className="mt-6 font-serif text-3xl text-[#103527]">{mode === "login" ? "Acesse sua operação" : "Crie sua conta"}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Entre no ambiente seguro e isolado da sua organização.</p><Button type="button" onClick={() => { window.location.href = "/api/auth/google"; }} variant="outline" className="mt-7 w-full border-[#c9a85b]/60 bg-[#fffdf7] text-[#103527] hover:bg-[#fbf5e6]"><Chrome className="mr-2 size-4" />Entrar com Google</Button><div className="my-6 flex items-center gap-3 text-xs text-muted-foreground before:h-px before:flex-1 before:bg-border after:h-px after:flex-1 after:bg-border">ou</div><form className="space-y-4" onSubmit={event => { event.preventDefault(); mode === "login" ? login.mutate({ email, password }) : register.mutate({ name, email, password }); }} >{mode === "register" && <div><Label>Nome</Label><Input required value={name} onChange={event => setName(event.target.value)} className="mt-1.5" /></div>}<div><Label>E-mail</Label><Input required type="email" value={email} onChange={event => setEmail(event.target.value)} className="mt-1.5" /></div><div><Label>Senha</Label><Input required type="password" minLength={10} value={password} onChange={event => setPassword(event.target.value)} className="mt-1.5" /></div><Button disabled={action.isPending} className="w-full bg-[#103527] hover:bg-[#174a35]">{mode === "login" ? "Entrar com e-mail" : "Criar conta"}</Button>{action.error && <p className="text-sm text-destructive">Verifique os dados informados e tente novamente.</p>}</form><button className="mt-6 w-full text-center text-sm text-[#466352] hover:underline" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "Ainda não tem conta? Cadastre-se" : "Já tem conta? Entrar"}</button></section></main>;
}
