import { EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { BarChart3, Flame, MapPinned, Plus, Send, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const heatClass = (value: number, max: number) => value <= 0 ? "bg-muted text-muted-foreground" : value >= max * .75 ? "bg-rose-600 text-white" : value >= max * .45 ? "bg-amber-500 text-white" : "bg-emerald-600 text-white";

export default function Mobilization() {
  const { activeCampaign } = useCampaign(); const utils = trpc.useUtils(); const [title, setTitle] = useState(""); const [question, setQuestion] = useState(""); const [kind, setKind] = useState<"single_choice" | "scale" | "text">("single_choice"); const [options, setOptions] = useState(""); const [classification, setClassification] = useState<"internal" | "public_disclosure">("internal"); const [registrationCode, setRegistrationCode] = useState(""); const [methodologySummary, setMethodologySummary] = useState(""); const [answers, setAnswers] = useState<Record<number, string>>({}); const [responseNeighborhood, setResponseNeighborhood] = useState(""); const [responseRegion, setResponseRegion] = useState(""); const [selectedSurveyId, setSelectedSurveyId] = useState<number | null>(null);
  const canManage = activeCampaign?.memberRole !== "partner";
  const heat = trpc.insights.heatmap.useQuery({ campaignId: activeCampaign?.id ?? 0 }, { enabled: Boolean(activeCampaign && canManage) });
  const scores = trpc.insights.mobilization.useQuery({ campaignId: activeCampaign?.id ?? 0 }, { enabled: Boolean(activeCampaign && canManage) });
  const surveys = trpc.insights.surveys.list.useQuery({ campaignId: activeCampaign?.id ?? 0 }, { enabled: Boolean(activeCampaign) });
  const surveySummary = trpc.insights.surveys.summary.useQuery({ campaignId: activeCampaign?.id ?? 0, surveyId: selectedSurveyId ?? 0 }, { enabled: Boolean(activeCampaign && selectedSurveyId && canManage) });
  const create = trpc.insights.surveys.create.useMutation({ onSuccess: async () => { await utils.insights.surveys.list.invalidate(); toast.success(classification === "public_disclosure" ? "Pesquisa salva para revisão humana antes de qualquer divulgação." : "Pesquisa criada."); setTitle(""); setQuestion(""); setOptions(""); setClassification("internal"); setRegistrationCode(""); setMethodologySummary(""); }, onError: error => toast.error(error.message) });
  const respond = trpc.insights.surveys.respond.useMutation({ onSuccess: async () => { await utils.insights.surveys.summary.invalidate(); toast.success("Resposta registrada."); }, onError: error => toast.error(error.message) });
  if (!activeCampaign) return <EmptyPanel title="Selecione uma campanha" description="Os dados de mobilização são isolados por campanha e organização." />;
  const max = Math.max(1, ...(heat.data ?? []).map(item => item.intensity));
  const submit = (event: FormEvent) => { event.preventDefault(); if (!canManage) return; if (classification === "public_disclosure" && (!registrationCode.trim() || methodologySummary.trim().length < 10)) { toast.error("Informe registro e metodologia antes de enviar pesquisa pública para revisão."); return; } create.mutate({ campaignId: activeCampaign.id, title, question, responseType: kind, options: kind === "single_choice" ? options.split(";").map(item => item.trim()).filter(Boolean) : undefined, status: classification === "public_disclosure" ? "draft" : "active", classification, registrationCode: classification === "public_disclosure" ? registrationCode || undefined : undefined, methodologySummary: classification === "public_disclosure" ? methodologySummary || undefined : undefined, disclosureText: classification === "public_disclosure" ? "Pesquisa destinada à divulgação; exige revisão humana e verificação de registro e metodologia." : undefined }); };
  return <section><PageHeader eyebrow="Inteligência de mobilização" title="Termômetro territorial" description="Combine presença de campo, relacionamento, consentimento e pesquisas rápidas para orientar a operação." />
    {canManage && <section className="mb-6 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><div className="min-w-0 flex-1"><Label htmlFor="survey-classification">Finalidade da próxima pesquisa</Label><select id="survey-classification" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={classification} onChange={event => setClassification(event.target.value as typeof classification)}><option value="internal">Uso interno da operação</option><option value="public_disclosure">Pretendida para divulgação pública</option></select><p className="mt-1 text-xs text-muted-foreground">Pesquisas públicas são salvas em rascunho e não podem ser divulgadas sem revisão humana.</p></div>{classification === "public_disclosure" && <><div className="min-w-0 flex-1"><Label htmlFor="survey-registration">Referência de registro</Label><Input id="survey-registration" className="mt-1" value={registrationCode} onChange={event => setRegistrationCode(event.target.value)} placeholder="Código ou referência aplicável" /></div><div className="min-w-0 flex-[1.4]"><Label htmlFor="survey-methodology">Metodologia resumida</Label><Input id="survey-methodology" className="mt-1" value={methodologySummary} onChange={event => setMethodologySummary(event.target.value)} placeholder="Amostra, período, método e responsável técnico" /></div></>}</div></section>}
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border bg-card p-5 shadow-sm"><Flame className="size-5 text-rose-600" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">Territórios ativos</p><p className="mt-1 text-3xl font-serif">{heat.data?.filter(item => item.intensity > 0).length ?? 0}</p></div><div className="rounded-2xl border bg-card p-5 shadow-sm"><Sparkles className="size-5 text-amber-600" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">Mobilizados</p><p className="mt-1 text-3xl font-serif">{scores.data?.filter(item => item.score >= 85).length ?? 0}</p></div><div className="rounded-2xl border bg-card p-5 shadow-sm"><BarChart3 className="size-5 text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">Pesquisas ativas</p><p className="mt-1 text-3xl font-serif">{surveys.data?.filter(item => item.status === "active").length ?? 0}</p></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><MapPinned className="size-5 text-primary" /><div><h2 className="font-semibold">Mapa de calor territorial</h2><p className="text-sm text-muted-foreground">Intensidade combina contatos, visitas, interações e respostas.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{(heat.data ?? []).map(item => <div key={`${item.region}-${item.neighborhood}`} className={`rounded-xl p-4 ${heatClass(item.intensity, max)}`}><p className="font-semibold">{item.neighborhood || "Sem bairro"}</p><p className="text-xs opacity-85">{item.region || "Sem região"}</p><p className="mt-3 text-2xl font-serif">{item.intensity}</p><p className="mt-1 text-xs opacity-85">{item.contacts} contatos · {item.visits} visitas · {item.interactions} interações</p></div>)}{!heat.data?.length && <EmptyPanel title="Sem dados territoriais" description="Cadastre contatos, visitas ou respostas com bairro e região para formar o mapa de calor." />}</div></div>
      <div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Sparkles className="size-5 text-amber-600" /><div><h2 className="font-semibold">Score de mobilização</h2><p className="text-sm text-muted-foreground">Pontuação explicável de 0 a 100.</p></div></div><div className="mt-4 space-y-2">{(scores.data ?? []).slice(0, 8).map(item => <div key={item.voter.id} className="flex items-center justify-between rounded-xl bg-muted/60 px-3 py-2"><div><p className="text-sm font-medium">{item.voter.name}</p><p className="text-xs text-muted-foreground">{item.interactions} interações · {item.visits} visitas · {item.consent ? "consentimento ativo" : "sem consentimento"}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${item.score >= 85 ? "bg-emerald-100 text-emerald-800" : item.score >= 55 ? "bg-amber-100 text-amber-800" : "bg-muted text-muted-foreground"}`}>{item.score}</span></div>)}{!scores.data?.length && <p className="py-8 text-center text-sm text-muted-foreground">Ainda não há contatos para calcular mobilização.</p>}</div></div></div>
    {canManage && surveys.data?.length ? <div className="mt-6 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold">Resumo da pesquisa por território</h2><p className="text-sm text-muted-foreground">Consolidação das respostas registradas com bairro e região.</p></div><select className="h-10 rounded-md border bg-background px-3 text-sm" value={selectedSurveyId ?? ""} onChange={event => setSelectedSurveyId(event.target.value ? Number(event.target.value) : null)}><option value="">Selecione uma pesquisa</option>{surveys.data.map(survey => <option key={survey.id} value={survey.id}>{survey.title}</option>)}</select></div>{selectedSurveyId ? <div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Respostas totais</p><p className="mt-1 font-serif text-3xl">{surveySummary.data?.total ?? 0}</p><div className="mt-3 space-y-1 text-sm text-muted-foreground">{(surveySummary.data?.answers ?? []).map(item => <p key={item.response}>{item.response}: <strong className="text-foreground">{item.total}</strong></p>)}</div></div><div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Distribuição territorial</p><div className="mt-2 space-y-2">{(surveySummary.data?.territories ?? []).slice(0, 6).map(item => <div key={`${item.region}-${item.neighborhood}`} className="flex items-center justify-between text-sm"><span>{item.neighborhood || "Sem bairro"} <span className="text-muted-foreground">· {item.region || "Sem região"}</span></span><strong>{item.total}</strong></div>)}{!surveySummary.data?.territories.length && <p className="text-sm text-muted-foreground">Ainda não há respostas territoriais registradas.</p>}</div></div></div> : <p className="mt-4 text-sm text-muted-foreground">Selecione uma pesquisa para analisar respostas e distribuição territorial.</p>}</div> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]">{canManage && <form onSubmit={submit} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Plus className="size-5 text-primary" /><h2 className="font-semibold">Pesquisa rápida</h2></div><div className="mt-4 space-y-3"><div><Label htmlFor="survey-title">Título</Label><Input id="survey-title" value={title} onChange={event => setTitle(event.target.value)} placeholder="Pulso de opinião do bairro" required /></div><div><Label htmlFor="survey-question">Pergunta</Label><Textarea id="survey-question" value={question} onChange={event => setQuestion(event.target.value)} placeholder="Qual demanda é mais urgente?" required /></div><div><Label htmlFor="survey-type">Tipo de resposta</Label><select id="survey-type" className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={kind} onChange={event => setKind(event.target.value as typeof kind)}><option value="single_choice">Escolha única</option><option value="scale">Escala</option><option value="text">Texto livre</option></select></div>{kind === "single_choice" && <div><Label htmlFor="survey-options">Opções separadas por ponto e vírgula</Label><Input id="survey-options" value={options} onChange={event => setOptions(event.target.value)} placeholder="Saúde; Segurança; Emprego" /></div>}<Button type="submit" className="w-full" disabled={create.isPending}>Ativar pesquisa</Button></div></form>}
      <div className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Coleta de respostas</h2><div className="mt-4 space-y-4">{(surveys.data ?? []).filter(item => item.status === "active").map(survey => <div key={survey.id} className="rounded-xl border p-4"><p className="font-medium">{survey.title}</p><p className="mt-1 text-sm text-muted-foreground">{survey.question}</p>{survey.responseType === "single_choice" && <select aria-label={`Resposta para ${survey.title}`} className="mt-3 h-10 w-full rounded-md border bg-background px-3 text-sm" value={answers[survey.id] ?? ""} onChange={event => setAnswers(current => ({ ...current, [survey.id]: event.target.value }))}><option value="">Selecione uma resposta</option>{((survey.options as string[] | null) ?? []).map(option => <option key={option} value={option}>{option}</option>)}</select>}{survey.responseType !== "single_choice" && <Input className="mt-3" aria-label={`Resposta para ${survey.title}`} value={answers[survey.id] ?? ""} onChange={event => setAnswers(current => ({ ...current, [survey.id]: event.target.value }))} placeholder={survey.responseType === "scale" ? "Informe uma nota de 1 a 5" : "Registre a resposta"} />}<div className="mt-3 grid gap-2 sm:grid-cols-2"><Input aria-label="Bairro da resposta" value={responseNeighborhood} onChange={event => setResponseNeighborhood(event.target.value)} placeholder="Bairro (opcional)" /><Input aria-label="Região da resposta" value={responseRegion} onChange={event => setResponseRegion(event.target.value)} placeholder="Região (opcional)" /></div><Button variant="outline" size="sm" className="mt-3" onClick={() => { const response = answers[survey.id]?.trim(); if (!response) return toast.error("Informe uma resposta antes de registrar."); respond.mutate({ surveyId: survey.id, campaignId: activeCampaign.id, response, neighborhood: responseNeighborhood || undefined, region: responseRegion || undefined }); setAnswers(current => ({ ...current, [survey.id]: "" })); }}><Send className="mr-2 size-4" />Registrar resposta</Button></div>)}{!surveys.data?.filter(item => item.status === "active").length && <EmptyPanel title="Nenhuma pesquisa ativa" description="Crie uma pergunta rápida para começar a captar sinais do território." />}</div></div></div>
  </section>;
}
