import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Building2, Loader2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";

export default function Onboarding() {
  const { user, loading } = useAuth(); const [, navigate] = useLocation(); const { data: organizations, isLoading } = trpc.organization.mine.useQuery(undefined, { enabled: !!user });
  const utils = trpc.useUtils(); const inviteToken = new URLSearchParams(window.location.search).get("invite"); const acceptingRef = useRef(false);
  const create = trpc.organization.create.useMutation({ onSuccess: data => { localStorage.setItem("w9-active-organization", String(data.organizationId)); navigate("/painel"); } });
  const accept = trpc.organization.invitations.accept.useMutation({ onSuccess: data => { localStorage.setItem("w9-active-organization", String(data.organizationId)); utils.organization.mine.invalidate(); navigate("/painel"); } });
  const [name, setName] = useState(""); const [legalName, setLegalName] = useState(""); const [fiscalId, setFiscalId] = useState("");
  useEffect(() => { if (!loading && !user) navigate("/login"); if (user && inviteToken && !acceptingRef.current) { acceptingRef.current = true; accept.mutate({ token: inviteToken }); } }, [loading, user, inviteToken, accept, navigate]);
  if (loading || isLoading) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="animate-spin text-[#103527]" /></div>;
  if (inviteToken && accept.isPending) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="animate-spin text-[#103527]" /></div>;
  if (organizations?.length) return <main className="min-h-screen bg-[#f8f7f2] px-5 py-16"><section className="mx-auto max-w-xl rounded-[2rem] border border-[#dbe5df] bg-white p-8 shadow-[0_30px_90px_-50px_rgba(16,53,39,.5)] sm:p-12"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#103527] text-[#e4cc8d]"><Building2 className="size-6" /></div><p className="mt-7 text-xs font-bold uppercase tracking-[.16em] text-[#9b7a32]">Selecione o ambiente</p><h1 className="mt-2 font-serif text-4xl text-[#103527]">Onde você quer trabalhar?</h1><div className="mt-7 space-y-3">{organizations.map(item => <button key={item.organization.id} onClick={() => { localStorage.setItem("w9-active-organization", String(item.organization.id)); navigate("/painel"); }} className="flex w-full items-center justify-between rounded-xl border border-[#dbe5df] p-4 text-left hover:border-[#c9a85b] hover:bg-[#fffaf0]"><span><strong className="block text-[#103527]">{item.organization.name}</strong><span className="text-xs text-muted-foreground">{item.organization.legalName || "Organização operacional"}</span></span><span className="text-xs capitalize text-[#466352]">{item.membership.role}</span></button>)}</div><Button variant="outline" className="mt-5 w-full" onClick={() => { setName(""); }}>Criar outra organização abaixo</Button><form className="mt-6 space-y-4 border-t pt-6" onSubmit={event => { event.preventDefault(); create.mutate({ name, legalName: legalName || undefined, fiscalId: fiscalId || undefined }); }}><Input required value={name} onChange={event => setName(event.target.value)} placeholder="Nome da nova organização" /><Button disabled={create.isPending} className="w-full bg-[#103527] hover:bg-[#174a35]">Criar nova organização</Button></form></section></main>;
  return <main className="min-h-screen bg-[#f8f7f2] px-5 py-16"><section className="mx-auto max-w-xl rounded-[2rem] border border-[#dbe5df] bg-white p-8 shadow-[0_30px_90px_-50px_rgba(16,53,39,.5)] sm:p-12"><div className="flex size-12 items-center justify-center rounded-2xl bg-[#103527] text-[#e4cc8d]"><Building2 className="size-6" /></div><p className="mt-7 text-xs font-bold uppercase tracking-[.16em] text-[#9b7a32]">Primeiro acesso</p><h1 className="mt-2 font-serif text-4xl text-[#103527]">Crie sua organização</h1><p className="mt-3 leading-6 text-muted-foreground">Sua organização mantém campanhas, contatos, conteúdos e equipe isolados de todos os demais clientes.</p><form className="mt-8 space-y-4" onSubmit={event => { event.preventDefault(); create.mutate({ name, legalName: legalName || undefined, fiscalId: fiscalId || undefined }); }}><div><Label>Nome da organização</Label><Input required value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: Movimento Cidade Viva" className="mt-1.5" /></div><div><Label>Razão social <span className="text-muted-foreground">(opcional)</span></Label><Input value={legalName} onChange={event => setLegalName(event.target.value)} className="mt-1.5" /></div><div><Label>CNPJ ou CPF <span className="text-muted-foreground">(opcional)</span></Label><Input value={fiscalId} onChange={event => setFiscalId(event.target.value)} className="mt-1.5" /></div><Button disabled={create.isPending} className="mt-3 w-full bg-[#103527] hover:bg-[#174a35]">{create.isPending ? "Criando ambiente..." : "Criar organização segura"}</Button>{(create.error || accept.error) && <p className="text-sm text-destructive">Não foi possível concluir esta ação. Verifique o convite ou tente novamente.</p>}</form></section></main>;
}
