import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Flag, Plus, Save, Target } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const statusLabel = { on_track: "No ritmo", attention: "Atenção", completed: "Concluída" } as const;

function OperationalGoalsContent() {
  const { activeCampaign } = useCampaign(); const campaignId = activeCampaign!.id; const utils = trpc.useUtils();
  const goals = trpc.goals.list.useQuery({ campaignId });
  const [form, setForm] = useState({ title: "", description: "", targetValue: "", unit: "entregas", deadline: "" });
  const [drafts, setDrafts] = useState<Record<number, string>>({});
  const canManage = activeCampaign?.memberRole !== "partner";
  const createGoal = trpc.goals.create.useMutation({ onSuccess: async () => { await Promise.all([utils.goals.list.invalidate({ campaignId }), utils.dashboard.dailyCoordination.invalidate({ campaignId })]); setForm({ title: "", description: "", targetValue: "", unit: "entregas", deadline: "" }); toast.success("Meta operacional criada."); }, onError: error => toast.error(error.message) });
  const updateProgress = trpc.goals.updateProgress.useMutation({ onSuccess: async () => { await Promise.all([utils.goals.list.invalidate({ campaignId }), utils.dashboard.dailyCoordination.invalidate({ campaignId }), utils.dashboard.summary.invalidate({ campaignId })]); toast.success("Progresso da meta atualizado."); }, onError: error => toast.error(error.message) });
  const rows = goals.data ?? [];
  const totals = useMemo(() => ({ total: rows.length, attention: rows.filter(item => item.status === "attention").length, completed: rows.filter(item => item.status === "completed").length }), [rows]);
  const submit = (event: FormEvent) => { event.preventDefault(); createGoal.mutate({ campaignId, title: form.title, description: form.description || undefined, targetValue: Number(form.targetValue), unit: form.unit, deadline: form.deadline ? new Date(`${form.deadline}T23:59:00`) : undefined }); };
  if (goals.isLoading) return <div className="h-80 animate-pulse rounded-2xl bg-muted" />;
  if (goals.isError) return <EmptyPanel title="Metas indisponíveis" description="Não foi possível carregar o monitor. Tente novamente." />;
  return <section><PageHeader eyebrow="Execução e acompanhamento" title="Metas operacionais" description="Defina resultados de operação, acompanhe o avanço e sinalize pontos que exigem atenção." />
    <div className="grid gap-4 sm:grid-cols-3"><Metric icon={Target} label="Metas ativas" value={totals.total - totals.completed} /><Metric icon={AlertTriangle} label="Em atenção" value={totals.attention} tone="text-amber-700" /><Metric icon={CheckCircle2} label="Concluídas" value={totals.completed} tone="text-emerald-700" /></div>
    {canManage && <form onSubmit={submit} className="mt-6 rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><Flag className="size-5" /></span><div><h2 className="font-semibold">Nova meta operacional</h2><p className="text-xs text-muted-foreground">Use objetivos mensuráveis, com unidade e prazo quando aplicável.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-medium">Título<Input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Ex.: Visitas confirmadas na região Norte" /></label><label className="grid gap-1 text-xs font-medium">Valor-alvo<Input required type="number" min="1" value={form.targetValue} onChange={event => setForm({ ...form, targetValue: event.target.value })} placeholder="Ex.: 120" /></label><label className="grid gap-1 text-xs font-medium">Unidade<Input required value={form.unit} onChange={event => setForm({ ...form, unit: event.target.value })} placeholder="Ex.: visitas" maxLength={40} /></label><label className="grid gap-1 text-xs font-medium">Prazo<Input type="date" value={form.deadline} onChange={event => setForm({ ...form, deadline: event.target.value })} /></label><label className="grid gap-1 text-xs font-medium md:col-span-2">Contexto<Textarea value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Como a equipe deve acompanhar esta meta?" maxLength={3000} rows={2} /></label></div><Button className="mt-4" type="submit" disabled={createGoal.isPending}><Plus className="mr-2 size-4" />{createGoal.isPending ? "Criando..." : "Criar meta"}</Button></form>}
    <div className="mt-6 grid gap-4 xl:grid-cols-2">{rows.map(goal => { const progress = goal.targetValue ? Math.min(100, Math.round((goal.currentValue / goal.targetValue) * 100)) : 0; const draft = drafts[goal.id] ?? String(goal.currentValue); const deadline = goal.deadline ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(goal.deadline) : "Sem prazo definido"; return <article key={goal.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{goal.title}</h2><p className="mt-1 text-xs text-muted-foreground">Prazo: {deadline}</p></div><Badge variant={goal.status === "attention" ? "destructive" : goal.status === "completed" ? "default" : "secondary"}>{statusLabel[goal.status]}</Badge></div>{goal.description && <p className="mt-3 text-sm text-muted-foreground">{goal.description}</p>}<div className="mt-5"><div className="flex justify-between text-sm"><span className="font-medium">{goal.currentValue} de {goal.targetValue} {goal.unit}</span><span className="text-muted-foreground">{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className={goal.status === "attention" ? "h-full bg-amber-500" : goal.status === "completed" ? "h-full bg-emerald-600" : "h-full bg-primary"} style={{ width: `${progress}%` }} /></div></div>{canManage && <div className="mt-5 flex flex-wrap items-end gap-2"><label className="grid gap-1 text-xs font-medium text-muted-foreground">Realizado<Input aria-label={`Realizado para ${goal.title}`} type="number" min="0" value={draft} onChange={event => setDrafts({ ...drafts, [goal.id]: event.target.value })} /></label><Button size="sm" variant="outline" disabled={updateProgress.isPending || Number(draft) === goal.currentValue} onClick={() => updateProgress.mutate({ campaignId, goalId: goal.id, currentValue: Math.max(0, Number(draft) || 0) })}><Save className="mr-1 size-3" />Atualizar</Button></div>}</article>; })}{!rows.length && <EmptyPanel title="Nenhuma meta cadastrada" description="Crie a primeira meta para acompanhar entregas, atividades e cobertura operacional." />}</div>
  </section>;
}
function Metric({ icon: Icon, label, value, tone = "text-primary" }: { icon: typeof Target; label: string; value: number; tone?: string }) { return <div className="rounded-2xl border bg-card p-5 shadow-sm"><Icon className={`size-5 ${tone}`} /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-serif text-3xl">{value}</p></div>; }
export default function OperationalGoals() { return <CampaignGate><OperationalGoalsContent /></CampaignGate>; }
