import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CalendarCheck2, CheckCircle2, MapPin, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRoute } from "wouter";

export default function PublicEventSignup() {
  const [, params] = useRoute("/evento/:eventId");
  const eventId = Number(params?.eventId ?? 0);
  const event = trpc.publicEvents.details.useQuery({ eventId }, { enabled: eventId > 0 });
  const registration = trpc.publicEvents.register.useMutation();
  const [form, setForm] = useState({ name: "", email: "", phone: "" });
  const submit = (input: FormEvent) => { input.preventDefault(); registration.mutate({ eventId, ...form, phone: form.phone || undefined }); };
  if (event.isLoading) return <main className="min-h-screen animate-pulse bg-[#f8f7f2]" />;
  if (!event.data) return <main className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><div className="max-w-md rounded-3xl border bg-card p-8 text-center"><CalendarCheck2 className="mx-auto size-10 text-primary" /><h1 className="mt-4 font-serif text-3xl">Evento indisponível</h1><p className="mt-3 text-sm text-muted-foreground">Este link não está ativo para inscrições no momento.</p></div></main>;
  const { event: details, campaign, registrationCount } = event.data;
  const closesAt = details.registrationClosesAt ? new Date(details.registrationClosesAt) : null;
  const isFull = Boolean(details.capacity && registrationCount >= details.capacity);
  const isClosed = Boolean(closesAt && closesAt < new Date());
  if (registration.isSuccess) return <main className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><div className="max-w-md rounded-3xl border border-emerald-200 bg-card p-8 text-center shadow-lg"><CheckCircle2 className="mx-auto size-11 text-emerald-600" /><h1 className="mt-5 font-serif text-3xl">{registration.data.alreadyRegistered ? "Inscrição já confirmada" : "Presença confirmada"}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{registration.data.alreadyRegistered ? "Este e-mail já estava inscrito. Nos vemos no evento." : "Sua inscrição foi registrada. Após o evento, use o link abaixo para enviar sua avaliação."}</p>{registration.data.accessToken && <a className="mt-6 inline-flex rounded-lg bg-[#103527] px-4 py-2 text-sm font-medium text-white" href={`/evento/feedback/${registration.data.accessToken}`}>Enviar avaliação depois do evento</a>}<p className="mt-4 text-xs text-muted-foreground">Guarde este link: ele identifica apenas sua participação e permite responder ao retorno pós-evento.</p></div></main>;
  return <main className="min-h-screen bg-[#f8f7f2] px-4 py-10"><section className="mx-auto max-w-2xl rounded-[2rem] border border-border bg-card p-6 shadow-[0_24px_80px_-45px_rgba(20,50,38,.55)] sm:p-9"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-[#103527] text-[#e4cc8d]"><CalendarCheck2 className="size-6" /></span><p className="font-serif text-lg">{campaign.name}</p></div><p className="mt-8 text-xs font-bold uppercase tracking-[.16em] text-primary">Confirmação de presença</p><h1 className="mt-2 font-serif text-3xl">{details.title}</h1><div className="mt-5 grid gap-3 rounded-2xl bg-muted/45 p-4 text-sm sm:grid-cols-2"><p className="flex gap-2"><CalendarCheck2 className="mt-0.5 size-4 text-primary" />{new Intl.DateTimeFormat("pt-BR", { dateStyle: "full", timeStyle: "short" }).format(new Date(details.startsAt))}</p><p className="flex gap-2"><MapPin className="mt-0.5 size-4 text-primary" />{details.location || "Local a confirmar"}</p>{details.capacity && <p className="flex gap-2 sm:col-span-2"><UsersRound className="mt-0.5 size-4 text-primary" />{Math.max(0, details.capacity - registrationCount)} vaga(s) disponível(is)</p>}</div><p className="mt-5 text-sm leading-6 text-muted-foreground">{details.notes || `Participe desta atividade da campanha de ${campaign.candidateName}.`}</p>{isFull || isClosed ? <div className="mt-7 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{isFull ? "As vagas deste evento foram preenchidas." : "As inscrições deste evento foram encerradas."}</div> : <form onSubmit={submit} className="mt-7 grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><label className="text-sm font-medium">Nome</label><Input required value={form.name} onChange={input => setForm({ ...form, name: input.target.value })} /></div><div className="space-y-2"><label className="text-sm font-medium">E-mail</label><Input required type="email" value={form.email} onChange={input => setForm({ ...form, email: input.target.value })} /></div><div className="space-y-2"><label className="text-sm font-medium">Telefone</label><Input value={form.phone} onChange={input => setForm({ ...form, phone: input.target.value })} /></div><p className="text-xs leading-5 text-muted-foreground sm:col-span-2">Usaremos os dados somente para confirmar sua participação neste evento e para o retorno pós-evento. Não há envio automático de mensagens por este formulário.</p><Button type="submit" disabled={registration.isPending} className="sm:col-span-2">{registration.isPending ? "Confirmando..." : "Confirmar presença"}</Button>{registration.error && <p className="text-sm text-destructive sm:col-span-2">{registration.error.message}</p>}</form>}</section></main>;
}
