import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRoute } from "wouter";

export default function PublicSignup() {
  const [, params] = useRoute("/cadastro/:campaignId");
  const campaignId = Number(params?.campaignId ?? 0);
  const { user, loading } = useAuth();
  const [form, setForm] = useState({ name: "", phone: "", email: "", neighborhood: "", region: "", consent: false });
  const { data, isLoading } = trpc.campaign.publicInfo.useQuery({ campaignId }, { enabled: campaignId > 0 });
  const submit = trpc.publicIntake.submit.useMutation();
  const onSubmit = (event: FormEvent) => { event.preventDefault(); submit.mutate({ campaignId, name: form.name, phone: form.phone || undefined, email: form.email || undefined, neighborhood: form.neighborhood || undefined, region: form.region || undefined, consent: true }); };
  if (isLoading || loading) return <div className="min-h-screen animate-pulse bg-[#f8f7f2]" />;
  if (!data) return <div className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><div className="max-w-md rounded-3xl border border-border bg-card p-8 text-center"><ShieldCheck className="mx-auto size-9 text-primary" /><h1 className="mt-4 font-serif text-3xl">Formulário indisponível</h1><p className="mt-3 text-sm text-muted-foreground">Este link não está ativo no momento.</p></div></div>;
  if (submit.isSuccess) return <div className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><div className="max-w-md rounded-3xl border border-emerald-200 bg-card p-8 text-center shadow-lg"><CheckCircle2 className="mx-auto size-11 text-emerald-600" /><h1 className="mt-5 font-serif text-3xl">Cadastro recebido</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Obrigado pelo interesse. Seus dados foram registrados para os fins informados, com base no seu consentimento.</p></div></div>;
  return <main className="min-h-screen bg-[#f8f7f2] px-4 py-10"><section className="mx-auto max-w-xl rounded-[2rem] border border-border bg-card p-6 shadow-[0_24px_80px_-45px_rgba(20,50,38,.55)] sm:p-9"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#103527] text-[#e4cc8d]"><ShieldCheck className="size-5" /></span><p className="font-serif text-lg">{data.name}</p></div><p className="mt-8 text-xs font-bold uppercase tracking-[.16em] text-primary">Cadastro de interesse</p><h1 className="mt-2 font-serif text-3xl">Participe da campanha de {data.candidateName}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Preencha apenas os dados necessários. Você pode retirar seu consentimento posteriormente pelos canais oficiais da campanha.</p><form onSubmit={onSubmit} className="mt-7 grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><label className="text-sm font-medium">Nome</label><Input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></div><div className="space-y-2"><label className="text-sm font-medium">Telefone</label><Input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></div><div className="space-y-2"><label className="text-sm font-medium">E-mail</label><Input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></div><div className="space-y-2"><label className="text-sm font-medium">Bairro</label><Input value={form.neighborhood} onChange={event => setForm({ ...form, neighborhood: event.target.value })} /></div><div className="space-y-2"><label className="text-sm font-medium">Região</label><Input value={form.region} onChange={event => setForm({ ...form, region: event.target.value })} /></div><label className="flex items-start gap-3 rounded-xl border border-border bg-muted/35 p-4 text-sm sm:col-span-2"><input required type="checkbox" checked={form.consent} onChange={event => setForm({ ...form, consent: event.target.checked })} className="mt-0.5 size-4 accent-primary" /><span>Autorizo o registro dos dados informados para contato e relacionamento institucional da campanha, conforme a finalidade apresentada.</span></label><Button type="submit" disabled={submit.isPending || !form.consent} className="sm:col-span-2">{submit.isPending ? "Enviando..." : "Enviar cadastro"}</Button>{submit.error && <p className="text-sm text-destructive sm:col-span-2">{submit.error.message}</p>}</form>{user && <p className="mt-6 text-center text-xs text-muted-foreground">Você está autenticado na plataforma.</p>}</section></main>;
}
