import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Building2, ExternalLink, FileText, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const proposalLabels = { draft: "Rascunho", sent: "Enviada", negotiation: "Negociação", accepted: "Aceita", lost: "Perdida", archived: "Arquivada" } as const;
const clientStatuses = ["active", "suspended", "archived"] as const;

export default function ResellerPanel() {
  const { user } = useAuth();
  const overview = trpc.reseller.overview.useQuery(undefined, { enabled: user?.role === "admin" });
  const utils = trpc.useUtils();
  const [clientForm, setClientForm] = useState({ name: "", legalName: "", fiscalId: "" });
  const [proposalForm, setProposalForm] = useState({ title: "", contactName: "", contactPhone: "", notes: "", organizationId: "none" });
  const createClient = trpc.reseller.clients.create.useMutation({ onSuccess: () => { toast.success("Cliente criado e vinculado ao revendedor."); setClientForm({ name: "", legalName: "", fiscalId: "" }); void utils.reseller.overview.invalidate(); }, onError: () => toast.error("Não foi possível criar o cliente.") });
  const updateClient = trpc.reseller.clients.update.useMutation({ onSuccess: () => { toast.success("Cliente atualizado."); void utils.reseller.overview.invalidate(); }, onError: () => toast.error("Não foi possível atualizar o cliente.") });
  const openSupport = trpc.reseller.clients.openSupport.useMutation({ onSuccess: ({ organizationId }) => { localStorage.setItem("w9-active-organization", String(organizationId)); toast.success("Acesso de suporte registrado na auditoria."); window.location.assign("/"); }, onError: () => toast.error("Não foi possível abrir o acesso de suporte.") });
  const createProposal = trpc.reseller.proposals.create.useMutation({ onSuccess: () => { toast.success("Proposta registrada."); setProposalForm({ title: "", contactName: "", contactPhone: "", notes: "", organizationId: "none" }); void utils.reseller.overview.invalidate(); }, onError: () => toast.error("Não foi possível registrar a proposta.") });
  const updateProposal = trpc.reseller.proposals.updateStatus.useMutation({ onSuccess: () => { void utils.reseller.overview.invalidate(); }, onError: () => toast.error("Não foi possível atualizar a proposta.") });

  if (user?.role !== "admin") return <Card><CardHeader><CardTitle>Acesso restrito</CardTitle><CardDescription>O painel de revendedor é reservado à administração da plataforma.</CardDescription></CardHeader></Card>;
  const data = overview.data;
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Gestão comercial</p><h1 className="mt-1 font-serif text-3xl font-semibold">Painel de revendedor</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Gerencie clientes vinculados, abertura de suporte auditável e o acompanhamento de propostas da plataforma.</p></div><Badge variant="outline" className="w-fit"><ShieldCheck className="mr-1 size-3.5" />Acesso de plataforma</Badge></div>
    <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><CardDescription>Clientes vinculados</CardDescription><CardTitle className="text-3xl">{data?.summary.totalClients ?? 0}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Clientes ativos</CardDescription><CardTitle className="text-3xl text-emerald-600">{data?.summary.activeClients ?? 0}</CardTitle></CardHeader></Card><Card><CardHeader className="pb-2"><CardDescription>Propostas em andamento</CardDescription><CardTitle className="text-3xl text-primary">{data?.summary.openProposals ?? 0}</CardTitle></CardHeader></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.05fr_1.45fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-4 text-primary" />Novo cliente</CardTitle><CardDescription>O cliente é criado como uma organização isolada e fica vinculado à sua operação de revenda.</CardDescription></CardHeader><CardContent className="space-y-3"><div><Label htmlFor="reseller-client-name">Nome da organização</Label><Input id="reseller-client-name" value={clientForm.name} onChange={event => setClientForm(current => ({ ...current, name: event.target.value }))} placeholder="Ex.: Comitê Municipal" /></div><div><Label htmlFor="reseller-client-legal">Razão social (opcional)</Label><Input id="reseller-client-legal" value={clientForm.legalName} onChange={event => setClientForm(current => ({ ...current, legalName: event.target.value }))} /></div><div><Label htmlFor="reseller-client-fiscal">Identificador fiscal (opcional)</Label><Input id="reseller-client-fiscal" value={clientForm.fiscalId} onChange={event => setClientForm(current => ({ ...current, fiscalId: event.target.value }))} /></div><Button className="w-full" disabled={clientForm.name.trim().length < 2 || createClient.isPending} onClick={() => createClient.mutate(clientForm)}>{createClient.isPending ? "Criando..." : "Criar cliente"}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="size-4 text-primary" />Organizações clientes</CardTitle><CardDescription>O suporte é registrado na auditoria e somente é aberto para organizações explicitamente vinculadas.</CardDescription></CardHeader><CardContent className="space-y-3">{overview.isLoading ? <p className="text-sm text-muted-foreground">Carregando clientes...</p> : data?.clients.length ? data.clients.map(({ client, organization }) => <div key={client.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{organization.name}</p><p className="mt-1 text-xs text-muted-foreground">#{organization.id} · {organization.legalName || "Sem razão social informada"}</p></div><div className="flex items-center gap-2"><Badge variant={organization.status === "active" ? "outline" : "secondary"}>{organization.status === "active" ? "Ativa" : organization.status === "suspended" ? "Suspensa" : "Arquivada"}</Badge><Button size="sm" variant="outline" disabled={openSupport.isPending || !client.active} onClick={() => openSupport.mutate({ organizationId: organization.id })}><ExternalLink className="mr-1.5 size-3.5" />Abrir suporte</Button></div></div><div className="mt-3 flex items-center gap-2"><Select value={organization.status} onValueChange={status => updateClient.mutate({ organizationId: organization.id, name: organization.name, legalName: organization.legalName, fiscalId: organization.fiscalId, status: status as (typeof clientStatuses)[number] })}><SelectTrigger className="h-8 w-40"><SelectValue /></SelectTrigger><SelectContent>{clientStatuses.map(status => <SelectItem key={status} value={status}>{status === "active" ? "Ativa" : status === "suspended" ? "Suspensa" : "Arquivada"}</SelectItem>)}</SelectContent></Select></div></div>) : <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhum cliente vinculado ainda.</div>}</CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-[1.05fr_1.45fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="size-4 text-primary" />Nova proposta</CardTitle><CardDescription>Registre o acompanhamento comercial sem expor valores financeiros na interface.</CardDescription></CardHeader><CardContent className="space-y-3"><div><Label htmlFor="proposal-title">Título</Label><Input id="proposal-title" value={proposalForm.title} onChange={event => setProposalForm(current => ({ ...current, title: event.target.value }))} placeholder="Ex.: Proposta campanha regional" /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="proposal-contact">Contato</Label><Input id="proposal-contact" value={proposalForm.contactName} onChange={event => setProposalForm(current => ({ ...current, contactName: event.target.value }))} /></div><div><Label htmlFor="proposal-phone">Telefone</Label><Input id="proposal-phone" value={proposalForm.contactPhone} onChange={event => setProposalForm(current => ({ ...current, contactPhone: event.target.value }))} /></div></div><div><Label htmlFor="proposal-client">Cliente relacionado</Label><Select value={proposalForm.organizationId} onValueChange={organizationId => setProposalForm(current => ({ ...current, organizationId }))}><SelectTrigger id="proposal-client"><SelectValue placeholder="Sem cliente vinculado" /></SelectTrigger><SelectContent><SelectItem value="none">Sem cliente vinculado</SelectItem>{data?.clients.map(({ organization }) => <SelectItem key={organization.id} value={String(organization.id)}>{organization.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="proposal-notes">Observações</Label><Textarea id="proposal-notes" value={proposalForm.notes} onChange={event => setProposalForm(current => ({ ...current, notes: event.target.value }))} /></div><Button className="w-full" disabled={proposalForm.title.trim().length < 2 || createProposal.isPending} onClick={() => createProposal.mutate({ ...proposalForm, organizationId: proposalForm.organizationId === "none" ? null : Number(proposalForm.organizationId) })}>{createProposal.isPending ? "Registrando..." : "Registrar proposta"}</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><UsersRound className="size-4 text-primary" />Acompanhamento de propostas</CardTitle><CardDescription>Atualize a etapa comercial sem dados de cobrança ou valores expostos.</CardDescription></CardHeader><CardContent className="space-y-3">{data?.proposals.length ? data.proposals.map(proposal => <div key={proposal.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{proposal.title}</p><p className="mt-1 text-xs text-muted-foreground">{proposal.contactName || "Contato não informado"}{proposal.contactPhone ? ` · ${proposal.contactPhone}` : ""}</p></div><Select value={proposal.status} onValueChange={status => updateProposal.mutate({ proposalId: proposal.id, status: status as keyof typeof proposalLabels })}><SelectTrigger className="w-40"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(proposalLabels).map(([status, label]) => <SelectItem key={status} value={status}>{label}</SelectItem>)}</SelectContent></Select></div>) : <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhuma proposta registrada.</div>}</CardContent></Card></div>
  </div>;
}
