import { EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { useCampaign } from "@/contexts/CampaignContext";
import { Calculator, CalendarDays, Target, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

export default function ScenarioSimulator() {
  const { activeCampaign } = useCampaign();
  const [visits, setVisits] = useState(120); const [contactsPerVisit, setContactsPerVisit] = useState(1); const [events, setEvents] = useState(4); const [audience, setAudience] = useState(80); const [engagementRate, setEngagementRate] = useState(35); const [mobilizationRate, setMobilizationRate] = useState(40); const [goal, setGoal] = useState(500);
  const scenario = useMemo(() => { const fieldContacts = visits * contactsPerVisit; const eventReach = events * audience; const engaged = Math.round((fieldContacts + eventReach) * (engagementRate / 100)); const mobilized = Math.round(engaged * (mobilizationRate / 100)); return { fieldContacts, eventReach, engaged, mobilized, progress: Math.min(100, Math.round((mobilized / Math.max(goal, 1)) * 100)) }; }, [visits, contactsPerVisit, events, audience, engagementRate, mobilizationRate, goal]);
  if (!activeCampaign) return <EmptyPanel title="Selecione uma campanha" description="As simulações ficam associadas à campanha em que a equipe está trabalhando." />;
  const numeric = (setter: (value: number) => void) => (event: React.ChangeEvent<HTMLInputElement>) => setter(Math.max(0, Number(event.target.value) || 0));
  return <section><PageHeader eyebrow="Planejamento estratégico" title="Simulador de cenários" description="Projete a capacidade de mobilização a partir de metas de campo, eventos e taxas explícitas de conversão." />
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Calculator className="size-5 text-primary" /><h2 className="font-semibold">Premissas do cenário</h2></div><p className="mt-1 text-sm text-muted-foreground">Ajuste os parâmetros abaixo. A projeção não substitui pesquisa eleitoral ou apuração oficial.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="scenario-visits">Visitas planejadas</Label><Input id="scenario-visits" type="number" min="0" value={visits} onChange={numeric(setVisits)} /></div><div><Label htmlFor="scenario-contact">Contatos por visita</Label><Input id="scenario-contact" type="number" min="0" step="0.1" value={contactsPerVisit} onChange={numeric(setContactsPerVisit)} /></div><div><Label htmlFor="scenario-events">Eventos planejados</Label><Input id="scenario-events" type="number" min="0" value={events} onChange={numeric(setEvents)} /></div><div><Label htmlFor="scenario-audience">Público médio por evento</Label><Input id="scenario-audience" type="number" min="0" value={audience} onChange={numeric(setAudience)} /></div><div><Label htmlFor="scenario-engagement">Conversão em engajamento (%)</Label><Input id="scenario-engagement" type="number" min="0" max="100" value={engagementRate} onChange={numeric(setEngagementRate)} /></div><div><Label htmlFor="scenario-mobilization">Conversão em mobilização (%)</Label><Input id="scenario-mobilization" type="number" min="0" max="100" value={mobilizationRate} onChange={numeric(setMobilizationRate)} /></div><div className="sm:col-span-2"><Label htmlFor="scenario-goal">Meta de mobilizados</Label><Input id="scenario-goal" type="number" min="1" value={goal} onChange={numeric(setGoal)} /></div></div><Button type="button" className="mt-5 w-full" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Atualizar projeção</Button></div>
      <div className="space-y-5"><div className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-2"><Target className="size-5 text-amber-600" /><h2 className="font-semibold">Projeção do cenário</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Metric icon={UsersRound} label="Contatos de campo" value={scenario.fieldContacts} detail="visitas × contatos por visita" /><Metric icon={CalendarDays} label="Alcance em eventos" value={scenario.eventReach} detail="eventos × público médio" /><Metric icon={UsersRound} label="Engajados estimados" value={scenario.engaged} detail={`${engagementRate}% do alcance estimado`} /><Metric icon={Target} label="Mobilizados estimados" value={scenario.mobilized} detail={`${mobilizationRate}% dos engajados`} /></div><div className="mt-6 rounded-xl bg-muted/60 p-4"><div className="flex items-center justify-between text-sm"><span className="font-medium">Atingimento da meta</span><span className="font-bold text-primary">{scenario.progress}%</span></div><Progress className="mt-3 h-2" value={scenario.progress} /><p className="mt-3 text-sm text-muted-foreground">O cenário alcança {scenario.mobilized.toLocaleString("pt-BR")} pessoas mobilizadas estimadas para uma meta de {goal.toLocaleString("pt-BR")}.</p></div></div><div className="rounded-2xl border border-primary/20 bg-primary/[.035] p-5"><h3 className="font-semibold">Como ler a projeção</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-muted-foreground"><li>• Contatos de campo e eventos são somados como potencial de alcance.</li><li>• As conversões são premissas ajustáveis e devem ser calibradas com dados reais da campanha.</li><li>• Use a Central de Consentimento e o Pipeline para transformar projeções em ações responsáveis.</li></ul></div></div></div>
  </section>;
}
function Metric({ icon: Icon, label, value, detail }: { icon: typeof UsersRound; label: string; value: number; detail: string }) { return <div className="rounded-xl border p-4"><Icon className="size-4 text-primary" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-serif text-3xl">{value.toLocaleString("pt-BR")}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
