import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { CheckSquare, KanbanSquare, List, Plus, Target } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const columns = [{ id: "backlog", label: "Backlog" }, { id: "todo", label: "A fazer" }, { id: "in_progress", label: "Em andamento" }, { id: "review", label: "Revisão" }, { id: "done", label: "Concluído" }] as const;
const priorityStyle = { low: "bg-slate-100 text-slate-700", medium: "bg-blue-50 text-blue-700", high: "bg-amber-50 text-amber-700", urgent: "bg-rose-50 text-rose-700" };
const priorityLabel = { low: "Baixa", medium: "Média", high: "Alta", urgent: "Urgente" };

function TasksContent() {
  const { activeCampaign } = useCampaign();
  const [view, setView] = useState<"kanban" | "list">("kanban");
  const [openForm, setOpenForm] = useState(false);
  const [showGoals, setShowGoals] = useState(true);
  const [openGoalForm, setOpenGoalForm] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", priority: "medium" as "low" | "medium" | "high" | "urgent", dueAt: "", assignedToId: "" });
  const [goalForm, setGoalForm] = useState({ title: "", description: "", targetValue: "", unit: "entregas", deadline: "" });
  const { data: taskList, isLoading, refetch } = trpc.tasks.list.useQuery({ campaignId: activeCampaign!.id });
  const { data: members } = trpc.team.list.useQuery({ campaignId: activeCampaign!.id });
  const { data: goalList, refetch: refetchGoals } = trpc.goals.list.useQuery({ campaignId: activeCampaign!.id });
  const createTask = trpc.tasks.create.useMutation({ onSuccess: () => { toast.success("Tarefa criada."); setOpenForm(false); setForm({ title: "", description: "", priority: "medium", dueAt: "", assignedToId: "" }); void refetch(); }, onError: error => toast.error(error.message) });
  const createGoal = trpc.goals.create.useMutation({ onSuccess: () => { toast.success("Meta criada."); setOpenGoalForm(false); setGoalForm({ title: "", description: "", targetValue: "", unit: "entregas", deadline: "" }); void refetchGoals(); }, onError: error => toast.error(error.message) });
  const updateStatus = trpc.tasks.updateStatus.useMutation({ onSuccess: () => void refetch(), onError: error => toast.error(error.message) });
  const canManage = activeCampaign?.memberRole !== "partner";
  const submit = (event: FormEvent) => { event.preventDefault(); createTask.mutate({ campaignId: activeCampaign!.id, title: form.title, description: form.description || undefined, priority: form.priority, dueAt: form.dueAt ? new Date(`${form.dueAt}T12:00`) : undefined, assignedToId: form.assignedToId ? Number(form.assignedToId) : undefined }); };
  const submitGoal = (event: FormEvent) => { event.preventDefault(); createGoal.mutate({ campaignId: activeCampaign!.id, title: goalForm.title, description: goalForm.description || undefined, targetValue: Number(goalForm.targetValue), unit: goalForm.unit, deadline: goalForm.deadline ? new Date(`${goalForm.deadline}T12:00`) : undefined }); };
  const cards = (items: typeof taskList) => items?.map(({ task, assignee }) => <article key={task.id} className="rounded-xl border border-border bg-card p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold leading-5">{task.title}</p><Badge className={priorityStyle[task.priority]}>{priorityLabel[task.priority]}</Badge></div>{task.description && <p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{task.description}</p>}<div className="mt-4 flex items-center justify-between gap-2 text-[11px] text-muted-foreground"><span>{assignee?.name || "Sem responsável"}</span><span>{task.dueAt ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(task.dueAt) : "Sem prazo"}</span></div><select aria-label="Atualizar status" value={task.status} onChange={event => updateStatus.mutate({ taskId: task.id, status: event.target.value as typeof task.status })} className="mt-3 h-8 w-full rounded border border-border bg-background px-2 text-xs">{columns.map(column => <option key={column.id} value={column.id}>{column.label}</option>)}</select></article>);
  return <>
    <PageHeader eyebrow="Execução e entregas" title="Metas e tarefas" description="Acompanhe o trabalho da equipe em lista ou no fluxo visual de kanban, com prazos e prioridades claros." action={<div className="flex gap-2"><div className="flex rounded-lg border border-border bg-card p-1"><Button size="sm" variant={view === "kanban" ? "secondary" : "ghost"} onClick={() => setView("kanban")}><KanbanSquare className="size-4" /></Button><Button size="sm" variant={view === "list" ? "secondary" : "ghost"} onClick={() => setView("list")}><List className="size-4" /></Button></div>{canManage && <Button variant="outline" onClick={() => setOpenGoalForm(value => !value)}><Target className="mr-2 size-4" />Nova meta</Button>}{canManage && <Button onClick={() => setOpenForm(value => !value)} className="bg-[#103527] text-white hover:bg-[#174a35]"><Plus className="mr-2 size-4" />Nova tarefa</Button>}</div>} />
    <section className="mb-6 rounded-2xl border border-border bg-card p-5"><button onClick={() => setShowGoals(value => !value)} className="flex w-full items-center justify-between text-left"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Target className="size-4" /></span><div><p className="font-semibold">Metas estratégicas</p><p className="mt-1 text-xs text-muted-foreground">Objetivos que orientam o ritmo de execução.</p></div></div><Badge variant="secondary">{goalList?.length ?? 0}</Badge></button>{showGoals && <>{openGoalForm && <form onSubmit={submitGoal} className="mt-5 grid gap-3 border-t border-border pt-5 md:grid-cols-2 xl:grid-cols-5"><div className="space-y-2"><Label>Meta</Label><Input required value={goalForm.title} onChange={event => setGoalForm({ ...goalForm, title: event.target.value })} /></div><div className="space-y-2"><Label>Valor-alvo</Label><Input required type="number" min="1" value={goalForm.targetValue} onChange={event => setGoalForm({ ...goalForm, targetValue: event.target.value })} /></div><div className="space-y-2"><Label>Unidade</Label><Input required value={goalForm.unit} onChange={event => setGoalForm({ ...goalForm, unit: event.target.value })} /></div><div className="space-y-2"><Label>Prazo</Label><Input type="date" value={goalForm.deadline} onChange={event => setGoalForm({ ...goalForm, deadline: event.target.value })} /></div><div className="flex items-end gap-2"><Button type="submit" disabled={createGoal.isPending}>{createGoal.isPending ? "Salvando..." : "Criar meta"}</Button><Button type="button" variant="outline" onClick={() => setOpenGoalForm(false)}>Cancelar</Button></div><div className="space-y-2 md:col-span-2 xl:col-span-5"><Label>Descrição</Label><Textarea value={goalForm.description} onChange={event => setGoalForm({ ...goalForm, description: event.target.value })} /></div></form>}{goalList?.length ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{goalList.map(goal => { const progress = goal.targetValue ? Math.min(100, Math.round((goal.currentValue / goal.targetValue) * 100)) : 0; return <article key={goal.id} className="rounded-xl bg-muted/45 p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold">{goal.title}</p><Badge variant="outline">{goal.currentValue}/{goal.targetValue}</Badge></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{progress}% · {goal.unit}{goal.deadline ? ` · até ${new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(goal.deadline)}` : ""}</p></article>; })}</div> : <p className="mt-5 text-sm text-muted-foreground">Ainda não há metas registradas. Crie um objetivo para acompanhar o progresso estratégico.</p>}</>}</section>
    {openForm && <form onSubmit={submit} className="mb-6 grid gap-4 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 md:grid-cols-2 xl:grid-cols-5"><div className="space-y-2"><Label htmlFor="task-title">Tarefa</Label><Input id="task-title" required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="task-assignee">Responsável</Label><select id="task-assignee" value={form.assignedToId} onChange={event => setForm({ ...form, assignedToId: event.target.value })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Definir depois</option>{members?.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="task-priority">Prioridade</Label><select id="task-priority" value={form.priority} onChange={event => setForm({ ...form, priority: event.target.value as typeof form.priority })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{Object.entries(priorityLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="space-y-2"><Label htmlFor="task-deadline">Prazo</Label><Input id="task-deadline" type="date" value={form.dueAt} onChange={event => setForm({ ...form, dueAt: event.target.value })} /></div><div className="flex items-end gap-2"><Button type="submit" className="flex-1" disabled={createTask.isPending}>{createTask.isPending ? "Criando..." : "Criar tarefa"}</Button><Button type="button" variant="outline" onClick={() => setOpenForm(false)}>Cancelar</Button></div><div className="space-y-2 md:col-span-2 xl:col-span-5"><Label htmlFor="task-description">Contexto</Label><Textarea id="task-description" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Descreva o resultado esperado e pontos de atenção." /></div></form>}
    {isLoading ? <div className="h-64 animate-pulse rounded-2xl bg-muted" /> : taskList?.length ? view === "kanban" ? <div className="grid gap-4 overflow-x-auto xl:grid-cols-5">{columns.map(column => <section key={column.id} className="min-w-56 rounded-2xl bg-muted/55 p-3"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{column.label}</p><Badge variant="secondary">{taskList.filter(item => item.task.status === column.id).length}</Badge></div><div className="space-y-3">{cards(taskList.filter(item => item.task.status === column.id))}</div></section>)}</div> : <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="grid grid-cols-[1.5fr_.7fr_.7fr_.7fr] gap-4 border-b border-border bg-muted/40 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-muted-foreground"><span>Tarefa</span><span>Status</span><span>Prioridade</span><span>Prazo</span></div>{taskList.map(({ task, assignee }) => <div key={task.id} className="grid grid-cols-[1.5fr_.7fr_.7fr_.7fr] items-center gap-4 border-b border-border/70 px-5 py-4 last:border-0"><div><p className="text-sm font-semibold">{task.title}</p><p className="mt-1 text-xs text-muted-foreground">{assignee?.name || "Sem responsável"}</p></div><select aria-label="Atualizar status" value={task.status} onChange={event => updateStatus.mutate({ taskId: task.id, status: event.target.value as typeof task.status })} className="h-8 rounded border border-border bg-background px-2 text-xs">{columns.map(column => <option key={column.id} value={column.id}>{column.label}</option>)}</select><Badge className={`w-fit ${priorityStyle[task.priority]}`}>{priorityLabel[task.priority]}</Badge><span className="text-xs text-muted-foreground">{task.dueAt ? new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(task.dueAt) : "—"}</span></div>)}</section> : <EmptyPanel title="Nenhuma tarefa registrada" description="Crie a primeira atividade para estruturar as entregas e o ritmo operacional da equipe." action={canManage ? <Button onClick={() => setOpenForm(true)}><CheckSquare className="mr-2 size-4" />Criar primeira tarefa</Button> : undefined} />}
  </>;
}
export default function Tasks() { return <CampaignGate><TasksContent /></CampaignGate>; }
