import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { Mail, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const roleText = { admin: "Administrador", coordinator: "Coordenador", partner: "Parceiro" };

function TeamContent() {
  const { activeCampaign } = useCampaign();
  const [isCreating, setIsCreating] = useState(false);
  const [editingCampaign, setEditingCampaign] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", role: "partner" as "admin" | "coordinator" | "partner", responsibility: "", workRegion: "" });
  const [campaignForm, setCampaignForm] = useState(() => ({ name: activeCampaign?.name ?? "", candidateName: activeCampaign?.candidateName ?? "", electionLabel: activeCampaign?.electionLabel ?? "", region: activeCampaign?.region ?? "", status: activeCampaign?.status ?? "planning" as "planning" | "active" | "paused" | "closed" }));
  const { data: members, isLoading, refetch } = trpc.team.list.useQuery({ campaignId: activeCampaign!.id });
  const createMember = trpc.team.create.useMutation({ onSuccess: () => { toast.success("Membro incluído na equipe."); setForm({ name: "", email: "", role: "partner", responsibility: "", workRegion: "" }); setIsCreating(false); void refetch(); }, onError: error => toast.error(error.message) });
  const updateCampaign = trpc.campaign.updateDetails.useMutation({ onSuccess: () => { toast.success("Dados da campanha atualizados."); setEditingCampaign(false); window.location.reload(); }, onError: error => toast.error(error.message) });
  const isAdmin = activeCampaign?.memberRole === "admin";
  const submit = (event: FormEvent) => { event.preventDefault(); createMember.mutate({ campaignId: activeCampaign!.id, ...form, responsibility: form.responsibility || undefined, workRegion: form.workRegion || undefined }); };
  return <>
    <PageHeader eyebrow="Estrutura da campanha" title="Equipe e responsabilidades" description="Centralize os membros operacionais, suas funções e os limites de acesso à campanha." action={isAdmin ? <div className="flex gap-2"><Button variant="outline" onClick={() => { setCampaignForm({ name: activeCampaign!.name, candidateName: activeCampaign!.candidateName, electionLabel: activeCampaign!.electionLabel, region: activeCampaign!.region, status: activeCampaign!.status }); setEditingCampaign(value => !value); }}>Editar campanha</Button><Button onClick={() => setIsCreating(value => !value)} className="bg-[#103527] text-white hover:bg-[#174a35]"><Plus className="mr-2 size-4" />Novo membro</Button></div> : undefined} />
    {editingCampaign && <form onSubmit={event => { event.preventDefault(); updateCampaign.mutate({ campaignId: activeCampaign!.id, ...campaignForm }); }} className="mb-6 grid gap-4 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 md:grid-cols-2 xl:grid-cols-5"><div className="space-y-2"><Label>Nome da campanha</Label><Input required value={campaignForm.name} onChange={event => setCampaignForm({ ...campaignForm, name: event.target.value })} /></div><div className="space-y-2"><Label>Candidato(a)</Label><Input required value={campaignForm.candidateName} onChange={event => setCampaignForm({ ...campaignForm, candidateName: event.target.value })} /></div><div className="space-y-2"><Label>Eleição / cargo</Label><Input required value={campaignForm.electionLabel} onChange={event => setCampaignForm({ ...campaignForm, electionLabel: event.target.value })} /></div><div className="space-y-2"><Label>Região-base</Label><Input required value={campaignForm.region} onChange={event => setCampaignForm({ ...campaignForm, region: event.target.value })} /></div><div className="space-y-2"><Label>Status</Label><select value={campaignForm.status} onChange={event => setCampaignForm({ ...campaignForm, status: event.target.value as typeof campaignForm.status })} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="planning">Planejamento</option><option value="active">Ativa</option><option value="paused">Pausada</option><option value="closed">Encerrada</option></select></div><div className="flex gap-2 md:col-span-2 xl:col-span-5"><Button type="submit" disabled={updateCampaign.isPending}>{updateCampaign.isPending ? "Atualizando..." : "Salvar dados"}</Button><Button type="button" variant="outline" onClick={() => setEditingCampaign(false)}>Cancelar</Button></div></form>}
    {isCreating && <form onSubmit={submit} className="mb-6 grid gap-4 rounded-2xl border border-primary/20 bg-primary/[.035] p-5 md:grid-cols-2 xl:grid-cols-5"><div className="space-y-2"><Label>Nome</Label><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></div><div className="space-y-2"><Label>E-mail</Label><Input type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} required /></div><div className="space-y-2"><Label>Função</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.role} onChange={event => setForm({ ...form, role: event.target.value as typeof form.role })}><option value="partner">Parceiro</option><option value="coordinator">Coordenador</option><option value="admin">Administrador</option></select></div><div className="space-y-2"><Label>Responsabilidade</Label><Input value={form.responsibility} onChange={event => setForm({ ...form, responsibility: event.target.value })} placeholder="Ex.: Agenda" /></div><div className="space-y-2"><Label>Região de trabalho</Label><Input value={form.workRegion} onChange={event => setForm({ ...form, workRegion: event.target.value })} placeholder="Ex.: Zona Norte" /></div><div className="flex items-end gap-2 md:col-span-2 xl:col-span-5"><Button type="submit" className="flex-1" disabled={createMember.isPending}>{createMember.isPending ? "Incluindo..." : "Salvar"}</Button><Button type="button" variant="outline" onClick={() => setIsCreating(false)}>Cancelar</Button></div></form>}
    <div className="mb-5 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-4"><ShieldCheck className="size-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{members?.filter(member => member.role === "admin").length ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">Administradores da campanha</p></div><div className="rounded-2xl border border-border bg-card p-4"><UsersRound className="size-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{members?.filter(member => member.role === "coordinator").length ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">Coordenadores táticos</p></div><div className="rounded-2xl border border-border bg-card p-4"><UsersRound className="size-5 text-primary" /><p className="mt-5 text-2xl font-semibold">{members?.filter(member => member.role === "partner").length ?? 0}</p><p className="mt-1 text-xs text-muted-foreground">Parceiros de campo</p></div></div>
    {isLoading ? <div className="h-64 animate-pulse rounded-2xl bg-muted" /> : members?.length ? <div className="grid gap-4 lg:grid-cols-2">{members.map(member => <article key={member.id} className="flex gap-4 rounded-2xl border border-border/75 bg-card p-5 shadow-[0_12px_28px_-24px_rgba(0,0,0,.6)]"><Avatar className="size-11 border"><AvatarFallback className="bg-primary/10 text-primary">{member.name.split(" ").slice(0, 2).map(item => item[0]).join("")}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="truncate font-semibold">{member.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Mail className="size-3" />{member.email}</p></div><Badge variant={member.role === "admin" ? "default" : "secondary"}>{roleText[member.role]}</Badge></div><div className="mt-4 grid gap-1 text-xs text-muted-foreground sm:grid-cols-2"><span>Responsabilidade: <strong className="font-medium text-foreground">{member.responsibility || "Não definida"}</strong></span><span>Região: <strong className="font-medium text-foreground">{member.workRegion || "Não definida"}</strong></span></div></div></article>)}</div> : <EmptyPanel title="A equipe ainda não possui membros cadastrados" description="Inclua coordenadores e parceiros, atribuindo responsabilidades e escopo territorial quando apropriado." action={isAdmin ? <Button onClick={() => setIsCreating(true)}><Plus className="mr-2 size-4" />Cadastrar membro</Button> : undefined} />}
  </>;
}
export default function Team() { return <CampaignGate><TeamContent /></CampaignGate>; }
