import { CampaignGate, EmptyPanel, PageHeader } from "@/components/CampaignShell";
import { Badge } from "@/components/ui/badge";
import { useCampaign } from "@/contexts/CampaignContext";
import { trpc } from "@/lib/trpc";
import { BarChart3, ShieldCheck, UsersRound } from "lucide-react";

function TeamBenchmarkContent() {
  const { activeCampaign } = useCampaign(); const benchmark = trpc.team.benchmark.useQuery({ campaignId: activeCampaign!.id });
  if (benchmark.isLoading) return <div className="h-80 animate-pulse rounded-2xl bg-muted" />;
  if (benchmark.isError) return <EmptyPanel title="Acesso restrito" description="O benchmark regional é exibido somente para perfis de gestão autorizados nesta campanha." />;
  const visible = (benchmark.data ?? []).filter(item => !item.suppressed); const max = Math.max(1, ...visible.map(item => item.productivityIndex ?? 0));
  return <section><PageHeader eyebrow="Gestão de equipe" title="Benchmark regional" description="Compare capacidade e entregas por região, sem identificar pessoas ou expor resultados de grupos pequenos." />
    <div className="grid gap-4 md:grid-cols-3"><Summary icon={UsersRound} label="Regiões avaliadas" value={visible.length} /><Summary icon={BarChart3} label="Índice médio" value={visible.length ? Math.round(visible.reduce((total, item) => total + (item.productivityIndex ?? 0), 0) / visible.length) : 0} /><Summary icon={ShieldCheck} label="Grupos protegidos" value={(benchmark.data ?? []).filter(item => item.suppressed).length} /></div>
    <div className="mt-6 rounded-2xl border border-primary/20 bg-primary/[.035] p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><div><h2 className="font-semibold">Proteção de privacidade</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Regiões com menos de dois integrantes ativos não apresentam indicadores de produtividade. O índice combina tarefas concluídas, eventos e visitas de campo por integrante; ele orienta a alocação da operação e não é uma avaliação individual.</p></div></div></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-2">{(benchmark.data ?? []).map(item => <article key={item.region} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-serif text-xl">{item.region}</h2><p className="mt-1 text-sm text-muted-foreground">{item.memberCount} integrante{item.memberCount === 1 ? "" : "s"} ativo{item.memberCount === 1 ? "" : "s"}</p></div><Badge variant={item.suppressed ? "secondary" : "outline"}>{item.suppressed ? "Dados protegidos" : "Comparável"}</Badge></div>{item.suppressed ? <p className="mt-7 rounded-xl bg-muted/60 p-4 text-sm leading-6 text-muted-foreground">São necessários ao menos dois integrantes ativos na região para liberar métricas agregadas.</p> : <><div className="mt-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Índice operacional</p><p className="mt-1 font-serif text-4xl">{item.productivityIndex}</p></div><p className="text-sm text-muted-foreground">por integrante</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.round(((item.productivityIndex ?? 0) / max) * 100)}%` }} /></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><Metric label="Tarefas" value={item.tasks ?? 0} /><Metric label="Concluídas" value={item.completed ?? 0} /><Metric label="Eventos" value={item.events ?? 0} /><Metric label="Visitas de campo" value={item.visits ?? 0} /></dl></>}</article>)}{!benchmark.data?.length && <EmptyPanel title="Ainda não há equipe regional" description="Defina a região de trabalho dos integrantes para formar grupos de benchmark protegidos." />}</div>
  </section>;
}
function Summary({ icon: Icon, label, value }: { icon: typeof UsersRound; label: string; value: number }) { return <div className="rounded-2xl border bg-card p-5 shadow-sm"><Icon className="size-5 text-primary" /><p className="mt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 font-serif text-3xl">{value}</p></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
export default function TeamBenchmark() { return <CampaignGate><TeamBenchmarkContent /></CampaignGate>; }
