import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, CheckCircle2, CircleCheck, ClipboardList, ExternalLink, FileText, HeartHandshake, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useRoute } from "wouter";
import { toast } from "sonner";

const trainingLabel = { not_started: "Formação ainda não iniciada", in_progress: "Formação em andamento", completed: "Formação concluída" } as const;
const statusLabel = { pending: "Inscrição em análise", active: "Cadastro ativo", inactive: "Cadastro inativo" } as const;
const assignmentLabel = { assigned: "Aguardando confirmação", accepted: "Tarefa aceita", completed: "Tarefa concluída", cancelled: "Tarefa cancelada" } as const;
const materialTypeLabel = { guide: "Guia", video: "Vídeo", checklist: "Checklist", link: "Material externo" } as const;

export default function VolunteerPortal() {
  const [, params] = useRoute("/voluntario/acesso/:token"); const token = params?.token ?? ""; const utils = trpc.useUtils(); const [availability, setAvailability] = useState(""); const [skills, setSkills] = useState("");
  const portal = trpc.volunteers.portal.useQuery({ token }, { enabled: token.length >= 32 }); const updateProfile = trpc.volunteers.updatePortalProfile.useMutation({ onSuccess: async () => { await utils.volunteers.portal.invalidate(); toast.success("Disponibilidade atualizada."); }, onError: error => toast.error(error.message) }); const updateTask = trpc.volunteers.updateOwnAssignmentStatus.useMutation({ onSuccess: async () => { await utils.volunteers.portal.invalidate(); toast.success("Tarefa atualizada."); }, onError: error => toast.error(error.message) }); const completeTraining = trpc.volunteers.completeTrainingMaterial.useMutation({ onSuccess: async result => { await utils.volunteers.portal.invalidate(); toast.success(result.trainingStatus === "completed" ? "Formação concluída. Obrigado por se preparar!" : "Material confirmado. Continue seu treinamento."); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (portal.data) { setAvailability(portal.data.volunteer.availability ?? ""); setSkills(portal.data.volunteer.skills ?? ""); } }, [portal.data]);
  const submit = (event: FormEvent) => { event.preventDefault(); updateProfile.mutate({ token, availability: availability || undefined, skills: skills || undefined }); };
  if (portal.isLoading) return <main className="min-h-screen animate-pulse bg-[#f8f7f2]" />;
  if (!portal.data) return <main className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><div className="max-w-md rounded-3xl border bg-card p-8 text-center"><ShieldCheck className="mx-auto size-10 text-primary" /><h1 className="mt-4 font-serif text-3xl">Acesso indisponível</h1><p className="mt-3 text-sm text-muted-foreground">Verifique se o link de acompanhamento está completo ou solicite um novo acesso à coordenação.</p></div></main>;
  const { volunteer, assignments, trainingMaterials } = portal.data; const completedMaterials = trainingMaterials.filter(item => item.completedAt).length; const trainingProgress = trainingMaterials.length ? Math.round((completedMaterials / trainingMaterials.length) * 100) : 0;
  return <main className="min-h-screen bg-[#f8f7f2] px-4 py-10"><section className="mx-auto max-w-3xl space-y-5"><header className="rounded-[2rem] border bg-card p-7 shadow-[0_24px_80px_-45px_rgba(20,50,38,.55)]"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-[#103527] text-[#e4cc8d]"><HeartHandshake className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Minha participação</p><h1 className="font-serif text-3xl">Olá, {volunteer.name}</h1></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Cadastro</p><p className="mt-1 font-medium">{statusLabel[volunteer.status]}</p></div><div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Formação</p><p className="mt-1 font-medium">{trainingLabel[volunteer.trainingStatus]}</p></div></div></header>
    <section className="rounded-2xl border bg-card p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex items-center gap-2"><BookOpenCheck className="size-5 text-primary" /><div><h2 className="font-serif text-2xl">Trilha de treinamento</h2><p className="text-sm text-muted-foreground">Leia os materiais de apoio e confirme sua conclusão em cada etapa.</p></div></div><span className="rounded-full bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">{completedMaterials}/{trainingMaterials.length} concluídos</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[#c9a85b] transition-[width] duration-300" style={{ width: `${trainingProgress}%` }} /></div>{trainingMaterials.length ? <div className="mt-5 space-y-3">{trainingMaterials.map((material, index) => <article key={material.id} className={`rounded-xl border p-4 ${material.completedAt ? "border-emerald-200 bg-emerald-50/30" : ""}`}><div className="flex flex-col justify-between gap-3 sm:flex-row"><div className="flex gap-3"><span className={`mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg ${material.completedAt ? "bg-emerald-600 text-white" : "bg-muted text-primary"}`}>{material.completedAt ? <CheckCircle2 className="size-4" /> : <FileText className="size-4" />}</span><div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Etapa {index + 1} · {materialTypeLabel[material.materialType]} · {material.durationMinutes} min</p><h3 className="mt-1 font-semibold">{material.title}</h3>{material.description && <p className="mt-1 text-sm text-muted-foreground">{material.description}</p>}</div></div>{material.completedAt && <span className="h-fit rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800">Concluído</span>}</div>{material.content && <details className="mt-4 rounded-lg bg-muted/55 p-3 text-sm"><summary className="cursor-pointer font-medium">Abrir material de apoio</summary><p className="mt-3 whitespace-pre-line leading-6 text-muted-foreground">{material.content}</p></details>}{material.resourceUrl && <a className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-primary underline-offset-4 hover:underline" href={material.resourceUrl} target="_blank" rel="noreferrer">Acessar material complementar <ExternalLink className="size-3" /></a>}{!material.completedAt && <div className="mt-4"><Button size="sm" disabled={completeTraining.isPending} onClick={() => completeTraining.mutate({ token, materialId: material.id })}><CircleCheck className="mr-2 size-4" />Confirmar conclusão</Button></div>}</article>)}</div> : <p className="mt-5 rounded-xl bg-muted/50 p-5 text-center text-sm text-muted-foreground">A coordenação ainda não publicou materiais de treinamento. Volte em breve para iniciar sua formação.</p>}</section>
    <form onSubmit={submit} className="rounded-2xl border bg-card p-6"><h2 className="font-serif text-2xl">Disponibilidade e habilidades</h2><p className="mt-1 text-sm text-muted-foreground">Mantenha suas informações atualizadas para que a equipe proponha atividades adequadas.</p><div className="mt-5 grid gap-4"><div><label className="text-sm font-medium">Disponibilidade</label><Textarea className="mt-2" value={availability} onChange={event => setAvailability(event.target.value)} /></div><div><label className="text-sm font-medium">Habilidades e áreas de interesse</label><Textarea className="mt-2" value={skills} onChange={event => setSkills(event.target.value)} /></div><Button type="submit" disabled={updateProfile.isPending}>{updateProfile.isPending ? "Salvando..." : "Atualizar informações"}</Button></div></form>
    <section className="rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><ClipboardList className="size-5 text-primary" /><div><h2 className="font-serif text-2xl">Minhas tarefas</h2><p className="text-sm text-muted-foreground">Confirme e conclua as atividades atribuídas pela coordenação.</p></div></div><div className="mt-5 space-y-3">{assignments.map(item => <article key={item.id} className="rounded-xl border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h3 className="font-medium">{item.title}</h3>{item.description && <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}<p className="mt-2 text-xs text-muted-foreground">{item.territory || "Território a definir"}{item.scheduledAt ? ` · ${new Date(item.scheduledAt).toLocaleDateString("pt-BR")}` : ""}</p></div><span className="h-fit rounded-full bg-muted px-3 py-1 text-xs font-medium">{assignmentLabel[item.status]}</span></div><div className="mt-3 flex gap-2">{item.status === "assigned" && <Button size="sm" variant="outline" disabled={updateTask.isPending} onClick={() => updateTask.mutate({ token, assignmentId: item.id, status: "accepted" })}>Aceitar tarefa</Button>}{item.status === "accepted" && <Button size="sm" disabled={updateTask.isPending} onClick={() => updateTask.mutate({ token, assignmentId: item.id, status: "completed" })}><CheckCircle2 className="mr-2 size-4" />Concluir tarefa</Button>}</div></article>)}{!assignments.length && <p className="rounded-xl bg-muted/50 p-5 text-center text-sm text-muted-foreground">A coordenação ainda não atribuiu tarefas. Quando houver uma atividade compatível com sua disponibilidade, ela aparecerá aqui.</p>}</div></section></section></main>;
}
