import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardList, HeartHandshake, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useRoute } from "wouter";
import { toast } from "sonner";

const trainingLabel = { not_started: "Formação ainda não iniciada", in_progress: "Formação em andamento", completed: "Formação concluída" } as const;
const statusLabel = { pending: "Inscrição em análise", active: "Cadastro ativo", inactive: "Cadastro inativo" } as const;
const assignmentLabel = { assigned: "Aguardando confirmação", accepted: "Tarefa aceita", completed: "Tarefa concluída", cancelled: "Tarefa cancelada" } as const;

export default function VolunteerPortal() {
  const [, params] = useRoute("/voluntario/acesso/:token"); const token = params?.token ?? ""; const utils = trpc.useUtils(); const [availability, setAvailability] = useState(""); const [skills, setSkills] = useState("");
  const portal = trpc.volunteers.portal.useQuery({ token }, { enabled: token.length >= 32 }); const updateProfile = trpc.volunteers.updatePortalProfile.useMutation({ onSuccess: async () => { await utils.volunteers.portal.invalidate(); toast.success("Disponibilidade atualizada."); }, onError: error => toast.error(error.message) }); const updateTask = trpc.volunteers.updateOwnAssignmentStatus.useMutation({ onSuccess: async () => { await utils.volunteers.portal.invalidate(); toast.success("Tarefa atualizada."); }, onError: error => toast.error(error.message) });
  useEffect(() => { if (portal.data) { setAvailability(portal.data.volunteer.availability ?? ""); setSkills(portal.data.volunteer.skills ?? ""); } }, [portal.data]);
  const submit = (event: FormEvent) => { event.preventDefault(); updateProfile.mutate({ token, availability: availability || undefined, skills: skills || undefined }); };
  if (portal.isLoading) return <main className="min-h-screen animate-pulse bg-[#f8f7f2]" />;
  if (!portal.data) return <main className="flex min-h-screen items-center justify-center bg-[#f8f7f2] p-5"><div className="max-w-md rounded-3xl border bg-card p-8 text-center"><ShieldCheck className="mx-auto size-10 text-primary" /><h1 className="mt-4 font-serif text-3xl">Acesso indisponível</h1><p className="mt-3 text-sm text-muted-foreground">Verifique se o link de acompanhamento está completo ou solicite um novo acesso à coordenação.</p></div></main>;
  const { volunteer, assignments } = portal.data;
  return <main className="min-h-screen bg-[#f8f7f2] px-4 py-10"><section className="mx-auto max-w-3xl space-y-5"><header className="rounded-[2rem] border bg-card p-7 shadow-[0_24px_80px_-45px_rgba(20,50,38,.55)]"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-[#103527] text-[#e4cc8d]"><HeartHandshake className="size-6" /></span><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Minha participação</p><h1 className="font-serif text-3xl">Olá, {volunteer.name}</h1></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Cadastro</p><p className="mt-1 font-medium">{statusLabel[volunteer.status]}</p></div><div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Formação</p><p className="mt-1 font-medium">{trainingLabel[volunteer.trainingStatus]}</p></div></div></header>
    <form onSubmit={submit} className="rounded-2xl border bg-card p-6"><h2 className="font-serif text-2xl">Disponibilidade e habilidades</h2><p className="mt-1 text-sm text-muted-foreground">Mantenha suas informações atualizadas para que a equipe proponha atividades adequadas.</p><div className="mt-5 grid gap-4"><div><label className="text-sm font-medium">Disponibilidade</label><Textarea className="mt-2" value={availability} onChange={event => setAvailability(event.target.value)} /></div><div><label className="text-sm font-medium">Habilidades e áreas de interesse</label><Textarea className="mt-2" value={skills} onChange={event => setSkills(event.target.value)} /></div><Button type="submit" disabled={updateProfile.isPending}>{updateProfile.isPending ? "Salvando..." : "Atualizar informações"}</Button></div></form>
    <section className="rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><ClipboardList className="size-5 text-primary" /><div><h2 className="font-serif text-2xl">Minhas tarefas</h2><p className="text-sm text-muted-foreground">Confirme e conclua as atividades atribuídas pela coordenação.</p></div></div><div className="mt-5 space-y-3">{assignments.map(item => <article key={item.id} className="rounded-xl border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h3 className="font-medium">{item.title}</h3>{item.description && <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}<p className="mt-2 text-xs text-muted-foreground">{item.territory || "Território a definir"}{item.scheduledAt ? ` · ${new Date(item.scheduledAt).toLocaleDateString("pt-BR")}` : ""}</p></div><span className="h-fit rounded-full bg-muted px-3 py-1 text-xs font-medium">{assignmentLabel[item.status]}</span></div><div className="mt-3 flex gap-2">{item.status === "assigned" && <Button size="sm" variant="outline" disabled={updateTask.isPending} onClick={() => updateTask.mutate({ token, assignmentId: item.id, status: "accepted" })}>Aceitar tarefa</Button>}{item.status === "accepted" && <Button size="sm" disabled={updateTask.isPending} onClick={() => updateTask.mutate({ token, assignmentId: item.id, status: "completed" })}><CheckCircle2 className="mr-2 size-4" />Concluir tarefa</Button>}</div></article>)}{!assignments.length && <p className="rounded-xl bg-muted/50 p-5 text-center text-sm text-muted-foreground">A coordenação ainda não atribuiu tarefas. Quando houver uma atividade compatível com sua disponibilidade, ela aparecerá aqui.</p>}</div></section></section></main>;
}
